UPDATE members SET riding_name = 'Abbotsford'
 WHERE riding_id = '898';
UPDATE members SET riding_name = 'Abitibi—Baie-James—Nunavik—Eeyou'
 WHERE riding_id = '637';
UPDATE members SET riding_name = 'Abitibi—Témiscamingue'
 WHERE riding_id = '638';
UPDATE members SET riding_name = 'Acadie—Bathurst'
 WHERE riding_id = '627';
UPDATE members SET riding_name = 'Ahuntsic-Cartierville'
 WHERE riding_id = '639';
UPDATE members SET riding_name = 'Ajax'
 WHERE riding_id = '715';
UPDATE members SET riding_name = 'Alfred-Pellan'
 WHERE riding_id = '640';
UPDATE members SET riding_name = 'Algoma—Manitoulin—Kapuskasing'
 WHERE riding_id = '716';
UPDATE members SET riding_name = 'Argenteuil—La Petite-Nation'
 WHERE riding_id = '641';
UPDATE members SET riding_name = 'Aurora—Oak Ridges—Richmond Hill'
 WHERE riding_id = '717';
UPDATE members SET riding_name = 'Avalon'
 WHERE riding_id = '605';
UPDATE members SET riding_name = 'Avignon—La Mitis—Matane—Matapédia'
 WHERE riding_id = '642';
UPDATE members SET riding_name = 'Banff—Airdrie'
 WHERE riding_id = '864';
UPDATE members SET riding_name = 'Barrie—Innisfil'
 WHERE riding_id = '718';
UPDATE members SET riding_name = 'Barrie—Springwater—Oro-Medonte'
 WHERE riding_id = '719';
UPDATE members SET riding_name = 'Battle River—Crowfoot'
 WHERE riding_id = '865';
UPDATE members SET riding_name = 'Battlefords—Lloydminster'
 WHERE riding_id = '850';
UPDATE members SET riding_name = 'Bay of Quinte'
 WHERE riding_id = '720';
UPDATE members SET riding_name = 'Beaches—East York'
 WHERE riding_id = '721';
UPDATE members SET riding_name = 'Beauce'
 WHERE riding_id = '643';
UPDATE members SET riding_name = 'Beauport—Côte-de-Beaupré—Île dOrléans—Charlevoix'
 WHERE riding_id = '656';
UPDATE members SET riding_name = 'Beauport—Limoilou'
 WHERE riding_id = '644';
UPDATE members SET riding_name = 'Beauséjour'
 WHERE riding_id = '628';
UPDATE members SET riding_name = 'Bécancour—Nicolet—Saurel'
 WHERE riding_id = '645';
UPDATE members SET riding_name = 'Bellechasse—Les Etchemins—Lévis'
 WHERE riding_id = '646';
UPDATE members SET riding_name = 'Beloeil—Chambly'
 WHERE riding_id = '647';
UPDATE members SET riding_name = 'Berthier—Maskinongé'
 WHERE riding_id = '648';
UPDATE members SET riding_name = 'Bonavista—Burin—Trinity'
 WHERE riding_id = '606';
UPDATE members SET riding_name = 'Bourassa'
 WHERE riding_id = '651';
UPDATE members SET riding_name = 'Bow River'
 WHERE riding_id = '866';
UPDATE members SET riding_name = 'Brampton Centre'
 WHERE riding_id = '722';
UPDATE members SET riding_name = 'Brampton East'
 WHERE riding_id = '723';
UPDATE members SET riding_name = 'Brampton North'
 WHERE riding_id = '724';
UPDATE members SET riding_name = 'Brampton South'
 WHERE riding_id = '725';
UPDATE members SET riding_name = 'Brampton West'
 WHERE riding_id = '726';
UPDATE members SET riding_name = 'Brandon—Souris'
 WHERE riding_id = '836';
UPDATE members SET riding_name = 'Brantford—Brant'
 WHERE riding_id = '727';
UPDATE members SET riding_name = 'Brome—Missisquoi'
 WHERE riding_id = '652';
UPDATE members SET riding_name = 'Brossard—Saint-Lambert'
 WHERE riding_id = '653';
UPDATE members SET riding_name = 'Bruce—Grey—Owen Sound'
 WHERE riding_id = '728';
UPDATE members SET riding_name = 'Burlington'
 WHERE riding_id = '729';
UPDATE members SET riding_name = 'Burnaby North—Seymour'
 WHERE riding_id = '899';
UPDATE members SET riding_name = 'Burnaby South'
 WHERE riding_id = '900';
UPDATE members SET riding_name = 'Calgary Centre'
 WHERE riding_id = '867';
UPDATE members SET riding_name = 'Calgary Confederation'
 WHERE riding_id = '868';
UPDATE members SET riding_name = 'Calgary Forest Lawn'
 WHERE riding_id = '869';
UPDATE members SET riding_name = 'Calgary Heritage'
 WHERE riding_id = '870';
UPDATE members SET riding_name = 'Calgary Midnapore'
 WHERE riding_id = '871';
UPDATE members SET riding_name = 'Calgary Nose Hill'
 WHERE riding_id = '872';
UPDATE members SET riding_name = 'Calgary Rocky Ridge'
 WHERE riding_id = '873';
UPDATE members SET riding_name = 'Calgary Shepard'
 WHERE riding_id = '874';
UPDATE members SET riding_name = 'Calgary Signal Hill'
 WHERE riding_id = '875';
UPDATE members SET riding_name = 'Calgary Skyview'
 WHERE riding_id = '876';
UPDATE members SET riding_name = 'Cambridge'
 WHERE riding_id = '730';
UPDATE members SET riding_name = 'Cape Breton—Canso'
 WHERE riding_id = '616';
UPDATE members SET riding_name = 'Cardigan'
 WHERE riding_id = '612';
UPDATE members SET riding_name = 'Cariboo—Prince George'
 WHERE riding_id = '901';
UPDATE members SET riding_name = 'Carleton'
 WHERE riding_id = '802';
UPDATE members SET riding_name = 'Carlton Trail—Eagle Creek'
 WHERE riding_id = '853';
UPDATE members SET riding_name = 'Central Nova'
 WHERE riding_id = '617';
UPDATE members SET riding_name = 'Central Okanagan—Similkameen—Nicola'
 WHERE riding_id = '902';
UPDATE members SET riding_name = 'Charlesbourg—Haute-Saint-Charles'
 WHERE riding_id = '655';
UPDATE members SET riding_name = 'Charleswood—St. James—Assiniboia—Headingley'
 WHERE riding_id = '837';
UPDATE members SET riding_name = 'Charlottetown'
 WHERE riding_id = '613';
UPDATE members SET riding_name = 'Châteauguay—Lacolle'
 WHERE riding_id = '657';
UPDATE members SET riding_name = 'Chatham-Kent—Leamington'
 WHERE riding_id = '731';
UPDATE members SET riding_name = 'Chicoutimi—Le Fjord'
 WHERE riding_id = '658';
UPDATE members SET riding_name = 'Chilliwack—Hope'
 WHERE riding_id = '903';
UPDATE members SET riding_name = 'Churchill—Keewatinook Aski'
 WHERE riding_id = '838';
UPDATE members SET riding_name = 'Cloverdale—Langley City'
 WHERE riding_id = '904';
UPDATE members SET riding_name = 'Coast of Bays—Central—Notre Dame'
 WHERE riding_id = '607';
UPDATE members SET riding_name = 'Compton—Stanstead'
 WHERE riding_id = '659';
UPDATE members SET riding_name = 'Coquitlam—Port Coquitlam'
 WHERE riding_id = '905';
UPDATE members SET riding_name = 'Courtenay—Alberni'
 WHERE riding_id = '906';
UPDATE members SET riding_name = 'Cowichan—Malahat—Langford'
 WHERE riding_id = '907';
UPDATE members SET riding_name = 'Cumberland—Colchester'
 WHERE riding_id = '618';
UPDATE members SET riding_name = 'Cypress Hills—Grasslands'
 WHERE riding_id = '851';
UPDATE members SET riding_name = 'Dartmouth—Cole Harbour'
 WHERE riding_id = '619';
UPDATE members SET riding_name = 'Dauphin—Swan River—Neepawa'
 WHERE riding_id = '839';
UPDATE members SET riding_name = 'Davenport'
 WHERE riding_id = '732';
UPDATE members SET riding_name = 'Delta'
 WHERE riding_id = '908';
UPDATE members SET riding_name = 'Desnethé—Missinippi—Churchill River'
 WHERE riding_id = '852';
UPDATE members SET riding_name = 'Don Valley East'
 WHERE riding_id = '733';
UPDATE members SET riding_name = 'Don Valley North'
 WHERE riding_id = '734';
UPDATE members SET riding_name = 'Don Valley West'
 WHERE riding_id = '735';
UPDATE members SET riding_name = 'Dorval—Lachine—LaSalle'
 WHERE riding_id = '660';
UPDATE members SET riding_name = 'Drummond'
 WHERE riding_id = '661';
UPDATE members SET riding_name = 'Dufferin—Caledon'
 WHERE riding_id = '736';
UPDATE members SET riding_name = 'Durham'
 WHERE riding_id = '737';
UPDATE members SET riding_name = 'Edmonton Centre'
 WHERE riding_id = '877';
UPDATE members SET riding_name = 'Edmonton Griesbach'
 WHERE riding_id = '878';
UPDATE members SET riding_name = 'Edmonton Manning'
 WHERE riding_id = '879';
UPDATE members SET riding_name = 'Edmonton Mill Woods'
 WHERE riding_id = '880';
UPDATE members SET riding_name = 'Edmonton Riverbend'
 WHERE riding_id = '881';
UPDATE members SET riding_name = 'Edmonton Strathcona'
 WHERE riding_id = '882';
UPDATE members SET riding_name = 'Edmonton West'
 WHERE riding_id = '883';
UPDATE members SET riding_name = 'Edmonton—Wetaskiwin'
 WHERE riding_id = '884';
UPDATE members SET riding_name = 'Eglinton—Lawrence'
 WHERE riding_id = '738';
UPDATE members SET riding_name = 'Egmont'
 WHERE riding_id = '614';
UPDATE members SET riding_name = 'Elgin—Middlesex—London'
 WHERE riding_id = '739';
UPDATE members SET riding_name = 'Elmwood—Transcona'
 WHERE riding_id = '840';
UPDATE members SET riding_name = 'Esquimalt—Saanich—Sooke'
 WHERE riding_id = '923';
UPDATE members SET riding_name = 'Essex'
 WHERE riding_id = '740';
UPDATE members SET riding_name = 'Etobicoke Centre'
 WHERE riding_id = '741';
UPDATE members SET riding_name = 'Etobicoke North'
 WHERE riding_id = '743';
UPDATE members SET riding_name = 'Etobicoke—Lakeshore'
 WHERE riding_id = '742';
UPDATE members SET riding_name = 'Flamborough—Glanbrook'
 WHERE riding_id = '744';
UPDATE members SET riding_name = 'Fleetwood—Port Kells'
 WHERE riding_id = '909';
UPDATE members SET riding_name = 'Foothills'
 WHERE riding_id = '885';
UPDATE members SET riding_name = 'Fort McMurray—Cold Lake'
 WHERE riding_id = '886';
UPDATE members SET riding_name = 'Fredericton'
 WHERE riding_id = '629';
UPDATE members SET riding_name = 'Fundy Royal'
 WHERE riding_id = '630';
UPDATE members SET riding_name = 'Gaspésie—Les Îles-de-la-Madeleine'
 WHERE riding_id = '662';
UPDATE members SET riding_name = 'Gatineau'
 WHERE riding_id = '663';
UPDATE members SET riding_name = 'Glengarry—Prescott—Russell'
 WHERE riding_id = '745';
UPDATE members SET riding_name = 'Grande Prairie—Mackenzie'
 WHERE riding_id = '887';
UPDATE members SET riding_name = 'Guelph'
 WHERE riding_id = '746';
UPDATE members SET riding_name = 'Haldimand—Norfolk'
 WHERE riding_id = '747';
UPDATE members SET riding_name = 'Haliburton—Kawartha Lakes—Brock'
 WHERE riding_id = '748';
UPDATE members SET riding_name = 'Halifax'
 WHERE riding_id = '620';
UPDATE members SET riding_name = 'Halifax West'
 WHERE riding_id = '621';
UPDATE members SET riding_name = 'Hamilton Centre'
 WHERE riding_id = '749';
UPDATE members SET riding_name = 'Hamilton East—Stoney Creek'
 WHERE riding_id = '750';
UPDATE members SET riding_name = 'Hamilton Mountain'
 WHERE riding_id = '751';
UPDATE members SET riding_name = 'Hamilton West—Ancaster—Dundas'
 WHERE riding_id = '752';
UPDATE members SET riding_name = 'Hastings—Lennox and Addington'
 WHERE riding_id = '753';
UPDATE members SET riding_name = 'Hochelaga'
 WHERE riding_id = '664';
UPDATE members SET riding_name = 'Honoré-Mercier'
 WHERE riding_id = '665';
UPDATE members SET riding_name = 'Hull—Aylmer'
 WHERE riding_id = '666';
UPDATE members SET riding_name = 'Humber River—Black Creek'
 WHERE riding_id = '835';
UPDATE members SET riding_name = 'Huron—Bruce'
 WHERE riding_id = '754';
UPDATE members SET riding_name = 'Joliette'
 WHERE riding_id = '667';
UPDATE members SET riding_name = 'Jonquière'
 WHERE riding_id = '668';
UPDATE members SET riding_name = 'Kamloops—Thompson—Cariboo'
 WHERE riding_id = '910';
UPDATE members SET riding_name = 'Kanata—Carleton'
 WHERE riding_id = '755';
UPDATE members SET riding_name = 'Kelowna—Lake Country'
 WHERE riding_id = '911';
UPDATE members SET riding_name = 'Kenora'
 WHERE riding_id = '756';
UPDATE members SET riding_name = 'Kildonan—St. Paul'
 WHERE riding_id = '841';
UPDATE members SET riding_name = 'Kings—Hants'
 WHERE riding_id = '622';
UPDATE members SET riding_name = 'Kingston and the Islands'
 WHERE riding_id = '758';
UPDATE members SET riding_name = 'King—Vaughan'
 WHERE riding_id = '757';
UPDATE members SET riding_name = 'Kitchener Centre'
 WHERE riding_id = '759';
UPDATE members SET riding_name = 'Kitchener South—Hespeler'
 WHERE riding_id = '761';
UPDATE members SET riding_name = 'Kitchener—Conestoga'
 WHERE riding_id = '760';
UPDATE members SET riding_name = 'Kootenay—Columbia'
 WHERE riding_id = '912';
UPDATE members SET riding_name = 'La Pointe-de-lÎle'
 WHERE riding_id = '669';
UPDATE members SET riding_name = 'La Prairie'
 WHERE riding_id = '670';
UPDATE members SET riding_name = 'Labrador'
 WHERE riding_id = '608';
UPDATE members SET riding_name = 'Lac-Saint-Jean'
 WHERE riding_id = '671';
UPDATE members SET riding_name = 'Lac-Saint-Louis'
 WHERE riding_id = '672';
UPDATE members SET riding_name = 'Lakeland'
 WHERE riding_id = '888';
UPDATE members SET riding_name = 'Lambton—Kent—Middlesex'
 WHERE riding_id = '762';
UPDATE members SET riding_name = 'Lanark—Frontenac—Kingston'
 WHERE riding_id = '763';
UPDATE members SET riding_name = 'Langley—Aldergrove'
 WHERE riding_id = '913';
UPDATE members SET riding_name = 'LaSalle—Émard—Verdun'
 WHERE riding_id = '673';
UPDATE members SET riding_name = 'Laurentides—Labelle'
 WHERE riding_id = '674';
UPDATE members SET riding_name = 'Laurier—Sainte-Marie'
 WHERE riding_id = '675';
UPDATE members SET riding_name = 'Laval—Les Îles'
 WHERE riding_id = '676';
UPDATE members SET riding_name = 'Leeds—Grenville—Thousand Islands and Rideau Lakes'
 WHERE riding_id = '764';
UPDATE members SET riding_name = 'Lethbridge'
 WHERE riding_id = '889';
UPDATE members SET riding_name = 'Lévis—Lotbinière'
 WHERE riding_id = '678';
UPDATE members SET riding_name = 'London North Centre'
 WHERE riding_id = '766';
UPDATE members SET riding_name = 'London West'
 WHERE riding_id = '767';
UPDATE members SET riding_name = 'London—Fanshawe'
 WHERE riding_id = '765';
UPDATE members SET riding_name = 'Long Range Mountains'
 WHERE riding_id = '609';
UPDATE members SET riding_name = 'Longueuil—Charles-LeMoyne'
 WHERE riding_id = '677';
UPDATE members SET riding_name = 'Longueuil—Saint-Hubert'
 WHERE riding_id = '679';
UPDATE members SET riding_name = 'Louis-Hébert'
 WHERE riding_id = '680';
UPDATE members SET riding_name = 'Louis-Saint-Laurent'
 WHERE riding_id = '681';
UPDATE members SET riding_name = 'Madawaska—Restigouche'
 WHERE riding_id = '631';
UPDATE members SET riding_name = 'Malpeque'
 WHERE riding_id = '615';
UPDATE members SET riding_name = 'Manicouagan'
 WHERE riding_id = '682';
UPDATE members SET riding_name = 'Marc-Aurèle-Fortin'
 WHERE riding_id = '701';
UPDATE members SET riding_name = 'Markham—Stouffville'
 WHERE riding_id = '768';
UPDATE members SET riding_name = 'Markham—Thornhill'
 WHERE riding_id = '769';
UPDATE members SET riding_name = 'Markham—Unionville'
 WHERE riding_id = '770';
UPDATE members SET riding_name = 'Medicine Hat—Cardston—Warner'
 WHERE riding_id = '890';
UPDATE members SET riding_name = 'Mégantic—LÉrable'
 WHERE riding_id = '683';
UPDATE members SET riding_name = 'Milton'
 WHERE riding_id = '771';
UPDATE members SET riding_name = 'Mirabel'
 WHERE riding_id = '684';
UPDATE members SET riding_name = 'Miramichi—Grand Lake'
 WHERE riding_id = '632';
UPDATE members SET riding_name = 'Mission—Matsqui—Fraser Canyon'
 WHERE riding_id = '914';
UPDATE members SET riding_name = 'Mississauga Centre'
 WHERE riding_id = '772';
UPDATE members SET riding_name = 'Mississauga East—Cooksville'
 WHERE riding_id = '773';
UPDATE members SET riding_name = 'Mississauga—Erin Mills'
 WHERE riding_id = '774';
UPDATE members SET riding_name = 'Mississauga—Lakeshore'
 WHERE riding_id = '775';
UPDATE members SET riding_name = 'Mississauga—Malton'
 WHERE riding_id = '776';
UPDATE members SET riding_name = 'Mississauga—Streetsville'
 WHERE riding_id = '777';
UPDATE members SET riding_name = 'Moncton—Riverview—Dieppe'
 WHERE riding_id = '633';
UPDATE members SET riding_name = 'Montarville'
 WHERE riding_id = '685';
UPDATE members SET riding_name = 'Montcalm'
 WHERE riding_id = '686';
UPDATE members SET riding_name = 'Montmagny—LIslet—Kamouraska—Rivière-du-Loup'
 WHERE riding_id = '687';
UPDATE members SET riding_name = 'Moose Jaw—Lake Centre—Lanigan'
 WHERE riding_id = '854';
UPDATE members SET riding_name = 'Mount Royal'
 WHERE riding_id = '688';
UPDATE members SET riding_name = 'Nanaimo—Ladysmith'
 WHERE riding_id = '915';
UPDATE members SET riding_name = 'Nepean'
 WHERE riding_id = '778';
UPDATE members SET riding_name = 'New Brunswick Southwest'
 WHERE riding_id = '634';
UPDATE members SET riding_name = 'New Westminster—Burnaby'
 WHERE riding_id = '916';
UPDATE members SET riding_name = 'Newmarket—Aurora'
 WHERE riding_id = '779';
UPDATE members SET riding_name = 'Niagara Centre'
 WHERE riding_id = '780';
UPDATE members SET riding_name = 'Niagara Falls'
 WHERE riding_id = '781';
UPDATE members SET riding_name = 'Niagara West'
 WHERE riding_id = '782';
UPDATE members SET riding_name = 'Nickel Belt'
 WHERE riding_id = '783';
UPDATE members SET riding_name = 'Nipissing—Timiskaming'
 WHERE riding_id = '784';
UPDATE members SET riding_name = 'North Island—Powell River'
 WHERE riding_id = '934';
UPDATE members SET riding_name = 'North Okanagan—Shuswap'
 WHERE riding_id = '917';
UPDATE members SET riding_name = 'North Vancouver'
 WHERE riding_id = '918';
UPDATE members SET riding_name = 'Northumberland—Peterborough South'
 WHERE riding_id = '785';
UPDATE members SET riding_name = 'Northwest Territories'
 WHERE riding_id = '941';
UPDATE members SET riding_name = 'Notre-Dame-de-Grâce—Westmount'
 WHERE riding_id = '689';
UPDATE members SET riding_name = 'Nunavut'
 WHERE riding_id = '942';
UPDATE members SET riding_name = 'Oakville'
 WHERE riding_id = '786';
UPDATE members SET riding_name = 'Oakville North—Burlington'
 WHERE riding_id = '787';
UPDATE members SET riding_name = 'Orléans'
 WHERE riding_id = '790';
UPDATE members SET riding_name = 'Oshawa'
 WHERE riding_id = '788';
UPDATE members SET riding_name = 'Ottawa Centre'
 WHERE riding_id = '789';
UPDATE members SET riding_name = 'Ottawa South'
 WHERE riding_id = '791';
UPDATE members SET riding_name = 'Ottawa West—Nepean'
 WHERE riding_id = '793';
UPDATE members SET riding_name = 'Ottawa—Vanier'
 WHERE riding_id = '792';
UPDATE members SET riding_name = 'Outremont'
 WHERE riding_id = '690';
UPDATE members SET riding_name = 'Oxford'
 WHERE riding_id = '794';
UPDATE members SET riding_name = 'Papineau'
 WHERE riding_id = '691';
UPDATE members SET riding_name = 'Parkdale—High Park'
 WHERE riding_id = '795';
UPDATE members SET riding_name = 'Parry Sound—Muskoka'
 WHERE riding_id = '796';
UPDATE members SET riding_name = 'Peace River—Westlock'
 WHERE riding_id = '891';
UPDATE members SET riding_name = 'Perth—Wellington'
 WHERE riding_id = '797';
UPDATE members SET riding_name = 'Peterborough—Kawartha'
 WHERE riding_id = '798';
UPDATE members SET riding_name = 'Pickering—Uxbridge'
 WHERE riding_id = '799';
UPDATE members SET riding_name = 'Pierre-Boucher—Les Patriotes—Verchères'
 WHERE riding_id = '650';
UPDATE members SET riding_name = 'Pierrefonds—Dollard'
 WHERE riding_id = '692';
UPDATE members SET riding_name = 'Pitt Meadows—Maple Ridge'
 WHERE riding_id = '919';
UPDATE members SET riding_name = 'Pontiac'
 WHERE riding_id = '693';
UPDATE members SET riding_name = 'Port Moody—Coquitlam'
 WHERE riding_id = '920';
UPDATE members SET riding_name = 'Portage—Lisgar'
 WHERE riding_id = '842';
UPDATE members SET riding_name = 'Portneuf—Jacques-Cartier'
 WHERE riding_id = '694';
UPDATE members SET riding_name = 'Prince Albert'
 WHERE riding_id = '855';
UPDATE members SET riding_name = 'Prince George—Peace River—Northern Rockies'
 WHERE riding_id = '921';
UPDATE members SET riding_name = 'Provencher'
 WHERE riding_id = '843';
UPDATE members SET riding_name = 'Québec'
 WHERE riding_id = '695';
UPDATE members SET riding_name = 'Red Deer—Lacombe'
 WHERE riding_id = '893';
UPDATE members SET riding_name = 'Red Deer—Mountain View'
 WHERE riding_id = '892';
UPDATE members SET riding_name = 'Regina—Lewvan'
 WHERE riding_id = '856';
UPDATE members SET riding_name = 'Regina—QuAppelle'
 WHERE riding_id = '857';
UPDATE members SET riding_name = 'Regina—Wascana'
 WHERE riding_id = '858';
UPDATE members SET riding_name = 'Renfrew—Nipissing—Pembroke'
 WHERE riding_id = '800';
UPDATE members SET riding_name = 'Repentigny'
 WHERE riding_id = '696';
UPDATE members SET riding_name = 'Richmond Centre'
 WHERE riding_id = '922';
UPDATE members SET riding_name = 'Richmond Hill'
 WHERE riding_id = '801';
UPDATE members SET riding_name = 'Richmond—Arthabaska'
 WHERE riding_id = '697';
UPDATE members SET riding_name = 'Rimouski-Neigette—Témiscouata—Les Basques'
 WHERE riding_id = '654';
UPDATE members SET riding_name = 'Rivière-des-Mille-Îles'
 WHERE riding_id = '698';
UPDATE members SET riding_name = 'Rivière-du-Nord'
 WHERE riding_id = '699';
UPDATE members SET riding_name = 'Rosemont—La Petite-Patrie'
 WHERE riding_id = '700';
UPDATE members SET riding_name = 'Saanich—Gulf Islands'
 WHERE riding_id = '924';
UPDATE members SET riding_name = 'Sackville—Preston—Chezzetcook'
 WHERE riding_id = '623';
UPDATE members SET riding_name = 'Saint Boniface—Saint Vital'
 WHERE riding_id = '844';
UPDATE members SET riding_name = 'Saint John—Rothesay'
 WHERE riding_id = '635';
UPDATE members SET riding_name = 'Saint-Hyacinthe—Bagot'
 WHERE riding_id = '702';
UPDATE members SET riding_name = 'Saint-Jean'
 WHERE riding_id = '703';
UPDATE members SET riding_name = 'Saint-Laurent'
 WHERE riding_id = '704';
UPDATE members SET riding_name = 'Saint-Léonard—Saint-Michel'
 WHERE riding_id = '705';
UPDATE members SET riding_name = 'Saint-Maurice—Champlain'
 WHERE riding_id = '706';
UPDATE members SET riding_name = 'Salaberry—Suroît'
 WHERE riding_id = '707';
UPDATE members SET riding_name = 'Sarnia—Lambton'
 WHERE riding_id = '805';
UPDATE members SET riding_name = 'Saskatoon West'
 WHERE riding_id = '861';
UPDATE members SET riding_name = 'Saskatoon—Grasswood'
 WHERE riding_id = '859';
UPDATE members SET riding_name = 'Saskatoon—University'
 WHERE riding_id = '860';
UPDATE members SET riding_name = 'Sault Ste. Marie'
 WHERE riding_id = '806';
UPDATE members SET riding_name = 'Scarborough Centre'
 WHERE riding_id = '808';
UPDATE members SET riding_name = 'Scarborough North'
 WHERE riding_id = '810';
UPDATE members SET riding_name = 'Scarborough Southwest'
 WHERE riding_id = '812';
UPDATE members SET riding_name = 'Scarborough—Agincourt'
 WHERE riding_id = '807';
UPDATE members SET riding_name = 'Scarborough—Guildwood'
 WHERE riding_id = '809';
UPDATE members SET riding_name = 'Scarborough—Rouge Park'
 WHERE riding_id = '811';
UPDATE members SET riding_name = 'Selkirk—Interlake—Eastman'
 WHERE riding_id = '845';
UPDATE members SET riding_name = 'Shefford'
 WHERE riding_id = '708';
UPDATE members SET riding_name = 'Sherbrooke'
 WHERE riding_id = '709';
UPDATE members SET riding_name = 'Sherwood Park—Fort Saskatchewan'
 WHERE riding_id = '895';
UPDATE members SET riding_name = 'Simcoe North'
 WHERE riding_id = '814';
UPDATE members SET riding_name = 'Simcoe—Grey'
 WHERE riding_id = '813';
UPDATE members SET riding_name = 'Skeena—Bulkley Valley'
 WHERE riding_id = '925';
UPDATE members SET riding_name = 'Souris—Moose Mountain'
 WHERE riding_id = '862';
UPDATE members SET riding_name = 'South Okanagan—West Kootenay'
 WHERE riding_id = '926';
UPDATE members SET riding_name = 'South Shore—St. Margarets'
 WHERE riding_id = '624';
UPDATE members SET riding_name = 'South Surrey—White Rock'
 WHERE riding_id = '927';
UPDATE members SET riding_name = 'Spadina—Fort York'
 WHERE riding_id = '815';
UPDATE members SET riding_name = 'St. Albert—Edmonton'
 WHERE riding_id = '894';
UPDATE members SET riding_name = 'St. Catharines'
 WHERE riding_id = '803';
UPDATE members SET riding_name = 'St. Johns East'
 WHERE riding_id = '610';
UPDATE members SET riding_name = 'St. Johns South—Mount Pearl'
 WHERE riding_id = '611';
UPDATE members SET riding_name = 'Steveston—Richmond East'
 WHERE riding_id = '928';
UPDATE members SET riding_name = 'Stormont—Dundas—South Glengarry'
 WHERE riding_id = '816';
UPDATE members SET riding_name = 'Sturgeon River—Parkland'
 WHERE riding_id = '896';
UPDATE members SET riding_name = 'Sudbury'
 WHERE riding_id = '817';
UPDATE members SET riding_name = 'Surrey Centre'
 WHERE riding_id = '929';
UPDATE members SET riding_name = 'Surrey—Newton'
 WHERE riding_id = '930';
UPDATE members SET riding_name = 'Sydney—Victoria'
 WHERE riding_id = '625';
UPDATE members SET riding_name = 'Terrebonne'
 WHERE riding_id = '711';
UPDATE members SET riding_name = 'Thérèse-De Blainville'
 WHERE riding_id = '649';
UPDATE members SET riding_name = 'Thornhill'
 WHERE riding_id = '818';
UPDATE members SET riding_name = 'Thunder Bay—Rainy River'
 WHERE riding_id = '819';
UPDATE members SET riding_name = 'Thunder Bay—Superior North'
 WHERE riding_id = '820';
UPDATE members SET riding_name = 'Timmins—James Bay'
 WHERE riding_id = '821';
UPDATE members SET riding_name = 'Tobique—Mactaquac'
 WHERE riding_id = '636';
UPDATE members SET riding_name = 'Toronto Centre'
 WHERE riding_id = '822';
UPDATE members SET riding_name = 'Toronto—Danforth'
 WHERE riding_id = '823';
UPDATE members SET riding_name = 'Toronto—St. Pauls'
 WHERE riding_id = '804';
UPDATE members SET riding_name = 'Trois-Rivières'
 WHERE riding_id = '712';
UPDATE members SET riding_name = 'University—Rosedale'
 WHERE riding_id = '824';
UPDATE members SET riding_name = 'Vancouver Centre'
 WHERE riding_id = '931';
UPDATE members SET riding_name = 'Vancouver East'
 WHERE riding_id = '932';
UPDATE members SET riding_name = 'Vancouver Granville'
 WHERE riding_id = '933';
UPDATE members SET riding_name = 'Vancouver Kingsway'
 WHERE riding_id = '935';
UPDATE members SET riding_name = 'Vancouver Quadra'
 WHERE riding_id = '936';
UPDATE members SET riding_name = 'Vancouver South'
 WHERE riding_id = '937';
UPDATE members SET riding_name = 'Vaudreuil—Soulanges'
 WHERE riding_id = '710';
UPDATE members SET riding_name = 'Vaughan—Woodbridge'
 WHERE riding_id = '825';
UPDATE members SET riding_name = 'Victoria'
 WHERE riding_id = '938';
UPDATE members SET riding_name = 'Ville-Marie—Le Sud-Ouest—Île-des-Soeurs'
 WHERE riding_id = '713';
UPDATE members SET riding_name = 'Vimy'
 WHERE riding_id = '714';
UPDATE members SET riding_name = 'Waterloo'
 WHERE riding_id = '826';
UPDATE members SET riding_name = 'Wellington—Halton Hills'
 WHERE riding_id = '827';
UPDATE members SET riding_name = 'West Nova'
 WHERE riding_id = '626';
UPDATE members SET riding_name = 'West Vancouver—Sunshine Coast—Sea to Sky Country'
 WHERE riding_id = '939';
UPDATE members SET riding_name = 'Whitby'
 WHERE riding_id = '828';
UPDATE members SET riding_name = 'Willowdale'
 WHERE riding_id = '829';
UPDATE members SET riding_name = 'Windsor West'
 WHERE riding_id = '831';
UPDATE members SET riding_name = 'Windsor—Tecumseh'
 WHERE riding_id = '830';
UPDATE members SET riding_name = 'Winnipeg Centre'
 WHERE riding_id = '846';
UPDATE members SET riding_name = 'Winnipeg North'
 WHERE riding_id = '847';
UPDATE members SET riding_name = 'Winnipeg South'
 WHERE riding_id = '848';
UPDATE members SET riding_name = 'Winnipeg South Centre'
 WHERE riding_id = '849';
UPDATE members SET riding_name = 'Yellowhead'
 WHERE riding_id = '897';
UPDATE members SET riding_name = 'York Centre'
 WHERE riding_id = '832';
UPDATE members SET riding_name = 'York South—Weston'
 WHERE riding_id = '834';
UPDATE members SET riding_name = 'York—Simcoe'
 WHERE riding_id = '833';
UPDATE members SET riding_name = 'Yorkton—Melville'
 WHERE riding_id = '863';
UPDATE members SET riding_name = 'Yukon'
 WHERE riding_id = '940';
