INSERT INTO members (name, riding_id, mp_id)
VALUES ('Abbotsford', 898, 35904);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Abitibi—Baie-James—Nunavik—Eeyou', 637, 71482);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Abitibi—Témiscamingue', 638, 232);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Acadie—Bathurst', 627, 88350);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Ahuntsic-Cartierville', 639, 88384);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Ajax', 715, 25508);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Alfred-Pellan', 640, 71337);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Algoma—Manitoulin—Kapuskasing', 716, 31289);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Argenteuil—La Petite-Nation', 641, 88394);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Aurora—Oak Ridges—Richmond Hill', 717, 88671);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Avalon', 605, 88283);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Avignon—La Mitis—Matane—Matapédia', 642, 88397);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Banff—Airdrie', 864, 59235);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Barrie—Innisfil', 718, 88674);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Barrie—Springwater—Oro-Medonte', 719, 88679);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Battle River—Crowfoot', 865, 1832);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Battlefords—Lloydminster', 850, 1209);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Bay of Quinte', 720, 88683);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Beaches—East York', 721, 88687);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Beauce', 643, 35309);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Beauport—Côte-de-Beaupré—Île d'Orléans—Charlevoix', 656, 35320);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Beauport—Limoilou', 644, 88404);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Beauséjour', 628, 1813);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Bécancour—Nicolet—Saurel', 645, 413);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Bellechasse—Les Etchemins—Lévis', 646, 35389);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Beloeil—Chambly', 647, 71368);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Berthier—Maskinongé', 648, 71357);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Bonavista—Burin—Trinity', 606, 58519);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Bourassa', 651, 84660);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Bow River', 866, 89109);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Brampton Centre', 722, 88692);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Brampton East', 723, 88694);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Brampton North', 724, 88698);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Brampton South', 725, 88703);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Brampton West', 726, 88705);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Brandon—Souris', 836, 7251);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Brantford—Brant', 727, 35539);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Brome—Missisquoi', 652, 198);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Brossard—Saint-Lambert', 653, 58621);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Bruce—Grey—Owen Sound', 728, 25522);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Burlington', 729, 88715);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Burnaby North—Seymour', 899, 89236);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Burnaby South', 900, 31701);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Calgary Centre', 867, 89111);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Calgary Confederation', 868, 89116);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Calgary Forest Lawn', 869, 1287);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Calgary Heritage', 870, 1733);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Calgary Midnapore', 871, 1302);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Calgary Nose Hill', 872, 71902);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Calgary Rocky Ridge', 873, 89130);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Calgary Shepard', 874, 89136);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Calgary Signal Hill', 875, 89139);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Calgary Skyview', 876, 89144);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Cambridge', 730, 71599);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Cape Breton—Canso', 616, 1804);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Cardigan', 612, 33);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Cariboo—Prince George', 901, 89249);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Carleton', 802, 25524);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Carlton Trail—Eagle Creek', 853, 59156);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Central Nova', 617, 88316);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Central Okanagan—Similkameen—Nicola', 902, 72029);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Charlesbourg—Haute-Saint-Charles', 655, 71454);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Charleswood—St. James—Assiniboia—Headingley', 837, 89027);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Charlottetown', 613, 71270);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Châteauguay—Lacolle', 657, 88442);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Chatham-Kent—Leamington', 731, 31765);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Chicoutimi—Le Fjord', 658, 88446);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Chilliwack—Hope', 903, 71986);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Churchill—Keewatinook Aski', 838, 36037);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Cloverdale—Langley City', 904, 89258);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Coast of Bays—Central—Notre Dame', 607, 25456);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Compton—Stanstead', 659, 88449);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Coquitlam—Port Coquitlam', 905, 59293);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Courtenay—Alberni', 906, 89263);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Cowichan—Malahat—Langford', 907, 89269);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Cumberland—Colchester', 618, 51);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Cypress Hills—Grasslands', 851, 1795);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Dartmouth—Cole Harbour', 619, 88323);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Dauphin—Swan River—Neepawa', 839, 69488);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Davenport', 732, 88721);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Delta', 908, 89272);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Desnethé—Missinippi—Churchill River', 852, 89065);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Don Valley East', 733, 25449);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Don Valley North', 734, 88726);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Don Valley West', 735, 58858);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Dorval—Lachine—LaSalle', 660, 88453);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Drummond', 661, 35351);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Dufferin—Caledon', 736, 25461);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Durham', 737, 72773);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Edmonton Centre', 877, 89147);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Edmonton Griesbach', 878, 89150);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Edmonton Manning', 879, 89156);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Edmonton Mill Woods', 880, 89163);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Edmonton Riverbend', 881, 89167);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Edmonton Strathcona', 882, 35873);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Edmonton West', 883, 89179);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Edmonton—Wetaskiwin', 884, 35857);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Eglinton—Lawrence', 738, 88738);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Egmont', 614, 88308);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Elgin—Middlesex—London', 739, 88742);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Elmwood—Transcona', 840, 89032);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Esquimalt—Saanich—Sooke', 923, 71995);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Essex', 740, 88745);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Etobicoke Centre', 741, 25468);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Etobicoke North', 743, 58877);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Etobicoke—Lakeshore', 742, 88748);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Flamborough—Glanbrook', 744, 31715);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Fleetwood—Port Kells', 909, 89274);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Foothills', 885, 86261);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Fort McMurray—Cold Lake', 886, 86260);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Fredericton', 629, 88355);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Fundy Royal', 630, 88357);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Gaspésie—Les Îles-de-la-Madeleine', 662, 88460);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Gatineau', 663, 88468);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Glengarry—Prescott—Russell', 745, 88756);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Grande Prairie—Mackenzie', 887, 35886);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Guelph', 746, 88761);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Haldimand—Norfolk', 747, 25501);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Haliburton—Kawartha Lakes—Brock', 748, 88770);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Halifax', 620, 88325);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Halifax West', 621, 1760);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Hamilton Centre', 749, 25489);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Hamilton East—Stoney Creek', 750, 88775);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Hamilton Mountain', 751, 88780);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Hamilton West—Ancaster—Dundas', 752, 88784);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Hastings—Lennox and Addington', 753, 88786);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Hochelaga', 664, 71395);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Honoré-Mercier', 665, 25451);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Hull—Aylmer', 666, 88478);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Humber River—Black Creek', 835, 1787);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Huron—Bruce', 754, 35600);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Joliette', 667, 88485);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Jonquière', 668, 88488);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Kamloops—Thompson—Cariboo', 910, 59265);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Kanata—Carleton', 755, 71602);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Kelowna—Lake Country', 911, 89279);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Kenora', 756, 709);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Kildonan—St. Paul', 841, 89037);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Kings—Hants', 622, 74);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Kingston and the Islands', 758, 88802);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('King—Vaughan', 757, 88799);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Kitchener Centre', 759, 88807);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Kitchener South—Hespeler', 761, 88813);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Kitchener—Conestoga', 760, 35607);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Kootenay—Columbia', 912, 89281);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('La Pointe-de-l'Île', 669, 376);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('La Prairie', 670, 88493);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Labrador', 608, 13218);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Lac-Saint-Jean', 671, 38633);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Lac-Saint-Louis', 672, 25453);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Lakeland', 888, 89198);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Lambton—Kent—Middlesex', 762, 31664);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Lanark—Frontenac—Kingston', 763, 1827);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Langley—Aldergrove', 913, 25467);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('LaSalle—Émard—Verdun', 673, 88501);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Laurentides—Labelle', 674, 88504);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Laurier—Sainte-Marie', 675, 71434);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Laval—Les Îles', 676, 88515);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Leeds—Grenville—Thousand Islands and Rideau Lakes', 764, 25483);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Lethbridge', 889, 89200);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Lévis—Lotbinière', 678, 35397);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('London North Centre', 766, 88827);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('London West', 767, 88832);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('London—Fanshawe', 765, 764);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Long Range Mountains', 609, 88292);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Longueuil—Charles-LeMoyne', 677, 88521);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Longueuil—Saint-Hubert', 679, 71447);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Louis-Hébert', 680, 88532);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Louis-Saint-Laurent', 681, 88535);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Madawaska—Restigouche', 631, 89383);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Malpeque', 615, 43);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Manicouagan', 682, 88538);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Marc-Aurèle-Fortin', 701, 88617);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Markham—Stouffville', 768, 88835);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Markham—Thornhill', 769, 1817);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Markham—Unionville', 770, 58878);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Medicine Hat—Cardston—Warner', 890, 0);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Mégantic—L'Érable', 683, 88541);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Milton', 771, 54325);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Mirabel', 684, 88544);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Miramichi—Grand Lake', 632, 88360);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Mission—Matsqui—Fraser Canyon', 914, 89288);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Mississauga Centre', 772, 89535);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Mississauga East—Cooksville', 773, 71692);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Mississauga—Erin Mills', 774, 88849);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Mississauga—Lakeshore', 775, 88852);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Mississauga—Malton', 776, 25471);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Mississauga—Streetsville', 777, 88858);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Moncton—Riverview—Dieppe', 633, 88364);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Montarville', 685, 71529);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Montcalm', 686, 88552);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Montmagny—L'Islet—Kamouraska—Rivière-du-Loup', 687, 63908);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Moose Jaw—Lake Centre—Lanigan', 854, 25520);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Mount Royal', 688, 88558);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Nanaimo—Ladysmith', 915, 89486);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Nepean', 778, 88860);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('New Brunswick Southwest', 634, 88365);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('New Westminster—Burnaby', 916, 16399);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Newmarket—Aurora', 779, 71702);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Niagara Centre', 780, 88867);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Niagara Falls', 781, 820);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Niagara West', 782, 25446);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Nickel Belt', 783, 88874);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Nipissing—Timiskaming', 784, 25452);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('North Island—Powell River', 934, 89354);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('North Okanagan—Shuswap', 917, 89294);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('North Vancouver', 918, 89300);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Northumberland—Peterborough South', 785, 71718);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Northwest Territories', 941, 89374);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Notre-Dame-de-Grâce—Westmount', 689, 10524);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Nunavut', 942, 1665);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Oakville', 786, 88881);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Oakville North—Burlington', 787, 88884);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Orléans', 790, 88894);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Oshawa', 788, 25486);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Ottawa Centre', 789, 88892);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Ottawa South', 791, 9486);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Ottawa West—Nepean', 793, 71738);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Ottawa—Vanier', 792, 873);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Outremont', 690, 26684);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Oxford', 794, 891);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Papineau', 691, 58733);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Parkdale—High Park', 795, 88910);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Parry Sound—Muskoka', 796, 15975);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Peace River—Westlock', 891, 89211);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Perth—Wellington', 797, 88917);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Peterborough—Kawartha', 798, 88922);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Pickering—Uxbridge', 799, 88925);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Pierre-Boucher—Les Patriotes—Verchères', 650, 88422);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Pierrefonds—Dollard', 692, 88578);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Pitt Meadows—Maple Ridge', 919, 89304);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Pontiac', 693, 89527);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Port Moody—Coquitlam', 920, 63592);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Portage—Lisgar', 842, 59110);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Portneuf—Jacques-Cartier', 694, 89407);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Prince Albert', 855, 59148);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Prince George—Peace River—Northern Rockies', 921, 72035);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Provencher', 843, 84672);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Québec', 695, 89408);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Red Deer—Lacombe', 893, 35897);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Red Deer—Mountain View', 892, 59226);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Regina—Lewvan', 856, 31796);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Regina—Qu'Appelle', 857, 25454);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Regina—Wascana', 858, 1265);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Renfrew—Nipissing—Pembroke', 800, 1809);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Repentigny', 696, 88595);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Richmond Centre', 922, 30812);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Richmond Hill', 801, 88929);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Richmond—Arthabaska', 697, 88600);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Rimouski-Neigette—Témiscouata—Les Basques', 654, 23915);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Rivière-des-Mille-Îles', 698, 88601);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Rivière-du-Nord', 699, 88605);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Rosemont—La Petite-Patrie', 700, 58775);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Saanich—Gulf Islands', 924, 2897);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Sackville—Preston—Chezzetcook', 623, 88333);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Saint Boniface—Saint Vital', 844, 89045);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Saint John—Rothesay', 635, 88368);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Saint-Hyacinthe—Bagot', 702, 53569);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Saint-Jean', 703, 88623);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Saint-Laurent', 704, 460);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Saint-Léonard—Saint-Michel', 705, 88627);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Saint-Maurice—Champlain', 706, 88633);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Salaberry—Suroît', 707, 71350);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Sarnia—Lambton', 805, 88938);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Saskatoon West', 861, 89090);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Saskatoon—Grasswood', 859, 89084);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Saskatoon—University', 860, 25462);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Sault Ste. Marie', 806, 88944);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Scarborough Centre', 808, 88950);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Scarborough North', 810, 88953);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Scarborough Southwest', 812, 88961);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Scarborough—Agincourt', 807, 86249);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Scarborough—Guildwood', 809, 957);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Scarborough—Rouge Park', 811, 89449);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Selkirk—Interlake—Eastman', 845, 25475);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Shefford', 708, 58707);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Sherbrooke', 709, 71553);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Sherwood Park—Fort Saskatchewan', 895, 89226);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Simcoe North', 814, 35724);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Simcoe—Grey', 813, 71786);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Skeena—Bulkley Valley', 925, 25493);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Souris—Moose Mountain', 862, 89095);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('South Okanagan—West Kootenay', 926, 89327);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('South Shore—St. Margarets', 624, 88340);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('South Surrey—White Rock', 927, 89333);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Spadina—Fort York', 815, 54434);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('St. Albert—Edmonton', 894, 89219);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('St. Catharines', 803, 88934);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('St. John's East', 610, 88296);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('St. John's South—Mount Pearl', 611, 88299);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Steveston—Richmond East', 928, 1825);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Stormont—Dundas—South Glengarry', 816, 25516);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Sturgeon River—Parkland', 896, 25447);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Sudbury', 817, 88973);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Surrey Centre', 929, 89339);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Surrey—Newton', 930, 31098);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Sydney—Victoria', 625, 1806);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Terrebonne', 711, 88651);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Thérèse-De Blainville', 649, 88419);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Thornhill', 818, 35699);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Thunder Bay—Rainy River', 819, 88982);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Thunder Bay—Superior North', 820, 88984);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Timmins—James Bay', 821, 25470);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Tobique—Mactaquac', 636, 88370);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Toronto Centre', 822, 88992);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Toronto—Danforth', 823, 88994);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Toronto—St. Paul's', 804, 992);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Trois-Rivières', 712, 71560);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('University—Rosedale', 824, 84665);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Vancouver Centre', 931, 1589);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Vancouver East', 932, 89346);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Vancouver Granville', 933, 89494);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Vancouver Kingsway', 935, 59325);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Vancouver Quadra', 936, 35950);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Vancouver South', 937, 89497);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Vaudreuil—Soulanges', 710, 88649);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Vaughan—Woodbridge', 825, 88999);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Victoria', 938, 60078);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Ville-Marie—Le Sud-Ouest—Île-des-Soeurs', 713, 88660);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Vimy', 714, 58806);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Waterloo', 826, 89000);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Wellington—Halton Hills', 827, 25488);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('West Nova', 626, 88346);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('West Vancouver—Sunshine Coast—Sea to Sky Country', 939, 89370);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Whitby', 828, 86786);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Willowdale', 829, 89010);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Windsor West', 831, 9137);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Windsor—Tecumseh', 830, 89012);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Winnipeg Centre', 846, 89466);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Winnipeg North', 847, 30552);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Winnipeg South', 848, 31119);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Winnipeg South Centre', 849, 89059);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Yellowhead', 897, 48292);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('York Centre', 832, 89018);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('York South—Weston', 834, 89020);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('York—Simcoe', 833, 25465);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Yorkton—Melville', 863, 89098);
INSERT INTO members (name, riding_id, mp_id)
VALUES ('Yukon', 940, 1796);
