INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
INSERT INTO members (mp_id, mp_name, vote, bill_voted_on)
VALUES ('', '', '', #{i['bill_vote']}');
