INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Ziad Aboultaif', 89156, 'C-223', 'An Act to establish the Canadian Organ Donor Registry and to coordinate and promote organ donation throughout Canada', 'Loi établissant le Registre canadien des donneurs d’organes et visant à coordonner et à promouvoir les dons d’organes au Canada', '2016-02-19', 8088970);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Dan Albas', 72029, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Harold Albrecht', 35607, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'John Aldag', 89258, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Omar Alghabra', 89535, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Leona Alleslev', 88671, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Dean Allison', 25446, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Rona Ambrose', 25447, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'William Amos', 89527, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Gary Anandasangaree', 89449, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'David Anderson', 1795, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Charlie Angus', 25470, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Mel Arnold', 89294, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'René Arseneault', 89383, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Chandra Arya', 88860, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Niki Ashton', 36037, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Robert Aubin', 71560, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Ramez Ayoub', 88419, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Vance Badawey', 88867, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Larry Bagnell', 1796, 'C-235', 'An Act to amend the Criminal Code and the Corrections and Conditional Release Act (fetal alcohol disorder)', 'Loi modifiant le Code criminel et la Loi sur le système correctionnel et la mise en liberté sous condition (troubles causés par l’alcoolisation foetale)', '2016-02-25', 8117624);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Navdeep Bains', 25471, 'C-11', 'An Act to amend the Copyright Act (access to copyrighted works or other subject-matter for persons with perceptual disabilities)', 'Loi modifiant la Loi sur le droit d'auteur (accès des personnes ayant des déficiences perceptuelles aux œuvres ou autres objets du droit d'auteur protégés)', '2016-03-24', 8164424);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'John Barlow', 86261, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Xavier Barsalou-Duval', 88422, 'C-275', 'An Act to amend the Income Tax Act (business transfer)', 'Loi modifiant la Loi de l’impôt sur le revenu (transmission d’entreprises)', '2016-05-19', 8283905);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Frank Baylis', 88578, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Mario Beaulieu', 376, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Terry Beech', 89236, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Mauril Bélanger', 873, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Carolyn Bennett', 992, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Sheri Benson', 89090, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Candice Bergen', 59110, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Maxime Bernier', 35309, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Luc Berthold', 88541, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'James Bezan', 25475, 'C-266', 'An Act to amend the Criminal Code (increasing parole ineligibility)', 'Loi modifiant le Code criminel (prolongation du délai préalable à la libération conditionnelle)', '2016-05-05', 8071171);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Marie-Claude Bibeau', 88449, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Chris Bittle', 88934, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Daniel Blaikie', 89032, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Bill Blair', 88961, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Steven Blaney', 35389, 'C-226', 'An Act to amend the Criminal Code (offences in relation to conveyances) and the Criminal Records Act and to make consequential amendments to other Acts', 'Loi modifiant le Code criminel (infractions relatives aux moyens de transport), la Loi sur le casier judiciaire et d’autres lois en conséquence', '2016-02-23', 8102913);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Rachel Blaney', 89354, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Kelly Block', 59156, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Randy Boissonnault', 89147, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Mike Bossio', 88786, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Sylvie Boucher', 35320, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Michel Boudrias', 88651, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Alexandre Boulerice', 58775, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Marjolaine Boutin-Sweet', 71395, 'C-264', 'An Act to amend the Canadian Bill of Rights (right to housing)', 'Loi modifiant la Déclaration canadienne des droits (droit au logement)', '2016-05-03', 8195181);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'John Brassard', 88674, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Bob Bratina', 88775, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Pierre Breton', 58707, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Scott Brison', 74, 'C-8', 'An Act for granting to Her Majesty certain sums of money for the federal public administration for the fiscal year ending March 31, 2016', 'Loi portant octroi à Sa Majesté de crédits pour l'administration publique fédérale pendant l'exercice se terminant le 31 mars 2016', '2016-03-21', 8160219);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Ruth Ellen Brosseau', 71357, 'C-231', 'An Act to establish National Food Waste Awareness Day and to provide for the development of a national strategy to reduce food waste in Canada', 'Loi instituant la Journée nationale de sensibilisation au gaspillage alimentaire et prévoyant l’élaboration d’une stratégie nationale visant à réduire le gaspillage alimentaire au Canada', '2016-02-24', 8112052);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Gord Brown', 25483, 'C-273', 'An Act to amend the Customs Act (marine pleasure craft)', 'Loi modifiant la Loi sur les douanes (embarcation de plaisance)', '2016-05-17', 8252661);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Celina Caesar-Chavannes', 86786, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Blaine Calkins', 35897, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Richard Cannings', 89327, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Guy Caron', 23915, 'C-274', 'An Act to amend the Income Tax Act (transfer of small business or family farm or fishing corporation)', 'Loi modifiant la Loi de l’impôt sur le revenu (transfert d'une petite entreprise ou d’une société agricole ou de pêche familiale)', '2016-05-19', 8283999);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Jim Carr', 89059, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Colin Carrie', 25486, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Bill Casey', 51, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Sean Casey', 71270, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Bardish Chagger', 89000, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'François-Philippe Champagne', 88633, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Arnold Chan', 86249, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Shaun Chen', 88953, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Michael Chong', 25488, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'François Choquette', 35351, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'David Christopherson', 25489, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Alupa Clarke', 88404, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Tony Clement', 15975, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Michael Cooper', 89219, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Serge Cormier', 88350, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Nathan Cullen', 25493, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Rodger Cuzner', 1804, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Julie Dabrusin', 88994, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Pam Damoff', 88884, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Don Davies', 59325, 'C-212', 'An Act to amend the Parliament of Canada Act (members who cross the floor)', 'Loi modifiant la Loi sur le Parlement du Canada (changement d'appartenance politique)', '2016-01-28', 8073171);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Matt DeCourcey', 88355, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Gérard Deltell', 88535, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Sukh Dhaliwal', 31098, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Anju Dhillon', 88453, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Nicola Di Iorio', 88627, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Stéphane Dion', 460, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Kerry Diotte', 89150, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Todd Doherty', 89249, 'C-211', 'An Act respecting a federal framework on post-traumatic stress disorder', 'Loi concernant un cadre fédéral relatif à l’état de stress post-traumatique', '2016-01-28', 8072201);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Fin Donnelly', 63592, 'C-228', 'An Act to amend the Fisheries Act (closed containment aquaculture)', 'Loi modifiant la Loi sur les pêches (aquaculture en parc clos)', '2016-02-24', 8107058);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Earl Dreeshen', 59226, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Francis Drouin', 88756, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Matthew Dubé', 71368, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Emmanuel Dubourg', 84660, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Jean-Yves Duclos', 89408, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Terry Duguid', 31119, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Kirsty Duncan', 58877, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Linda Duncan', 35873, 'C-202', 'An Act to establish a Canadian Environmental Bill of Rights and to make a related amendment to another Act', 'Loi portant création de la Charte canadienne des droits environnementaux et apportant une modification connexe à une autre loi', '2015-12-09', 8061008);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Pierre-Luc Dusseault', 71553, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Scott Duvall', 88780, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Julie Dzerowicz', 88721, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Wayne Easter', 43, 'C-253', 'An Act to Recognize Charlottetown as the Birthplace of Confederation', 'Loi visant à reconnaître Charlottetown comme le berceau de la Confédération', '2016-03-24', 8160524);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Jim Eglinski', 48292, 'C-206', 'An Act to amend the Criminal Code (abuse of vulnerable persons)', 'Loi modifiant le Code criminel (mauvais traitement de personnes vulnérables)', '2015-12-10', 8060518);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Ali Ehsassi', 89010, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Fayçal El-Khoury', 88515, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Neil Ellis', 88683, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Nathaniel Erskine-Smith', 88687, 'C-246', 'An Act to amend the Criminal Code, the Fisheries Act, the Textile Labelling Act, the Wild Animal and Plant Protection and Regulation of International and Interprovincial Trade Act and the Canada Consumer Product Safety Act (animal protection)', 'Loi modifiant le Code criminel, la Loi sur les pêches, la Loi sur l'étiquetage des textiles, la Loi sur la protection d'espèces animales ou végétales sauvages et la réglementation de leur commerce international et interprovincial et la Loi canadienne sur la sécurité des produits de consommation (protection des animaux)', '2016-02-26', 8122718);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Mark Eyking', 1806, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Doug Eyolfson', 89027, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Ted Falk', 84672, 'C-239', 'An Act to amend the Income Tax Act (charitable gifts)', 'Loi modifiant la Loi de l’impôt sur le revenu (dons de bienfaisance)', '2016-02-25', 8119035);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Ed Fast', 35904, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Greg Fergus', 88478, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Andy Fillmore', 88325, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Diane Finley', 25501, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Pat Finnigan', 88360, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Darren Fisher', 88323, 'C-238', 'An Act respecting the development of a national strategy for the safe disposal of lamps containing mercury', 'Loi concernant l’élaboration d’une stratégie nationale sur l’élimination sécuritaire des lampes contenant du mercure', '2016-02-25', 8118993);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Peter Fonseca', 71692, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Judy Foote', 58519, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Rhéal Fortin', 88605, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Peter Fragiskatos', 88827, 'C-242', 'An Act to amend the Criminal Code (inflicting torture)', 'Loi modifiant le Code criminel (recours à la torture)', '2016-02-26', 8122740);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Colin Fraser', 88346, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Sean Fraser', 88316, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Chrystia Freeland', 84665, 'C-13', 'An Act to amend the Food and Drugs Act, the Hazardous Products Act, the Radiation Emitting Devices Act, the Canadian Environmental Protection Act, 1999, the Pest Control Products Act and the Canada Consumer Product Safety Act and to make related amendments to another Act', 'Loi modifiant la Loi sur les aliments et drogues, la Loi sur les produits dangereux, la Loi sur les dispositifs émettant des radiations, la Loi canadienne sur la protection de l'environnement (1999), la Loi sur les produits antiparasitaires et la Loi canadienne sur la sécurité des produits de consommation et apportant des modifications connexes à une autre loi', '2016-04-13', 8173019);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Hedy Fry', 1589, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Stephen Fuhr', 89279, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Cheryl Gallant', 1809, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Marc Garneau', 10524, 'C-10', 'An Act to amend the Air Canada Public Participation Act and to provide for certain other measures', 'Loi modifiant la Loi sur la participation publique au capital d'Air Canada et comportant d'autres mesures', '2016-03-24', 8139986);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Randall Garrison', 71995, 'C-204', 'An Act to amend the Canadian Human Rights Act and the Criminal Code (gender identity and gender expression)', 'Loi modifiant la Loi canadienne sur les droits de la personne et le Code criminel (identité et expression de genre)', '2015-12-09', 8060626);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Bernard Généreux', 63908, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Garnett Genuis', 89226, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Mark Gerretsen', 88802, 'C-243', 'An Act respecting the development of a national maternity assistance program strategy and amending the Employment Insurance Act (maternity benefits)', 'Loi visant l’élaboration d’une stratégie relative au programme national d’aide à la maternité et modifiant la Loi sur l’assurance-emploi (prestations de maternité)', '2016-02-26', 8122307);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Marilène Gill', 88538, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Marilyn Gladu', 88938, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Joël Godin', 89407, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Pam Goldsmith-Jones', 89370, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Ralph Goodale', 1265, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Karina Gould', 88715, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Jacques Gourde', 35397, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'David Graham', 88504, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Raj Grewal', 88694, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Patty Hajdu', 88984, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Cheryl Hardcastle', 89012, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Rachael Harder', 89200, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Ken Hardie', 89274, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Stephen Harper', 1733, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'TJ Harvey', 88370, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Kent Hehr', 89111, 'C-12', 'An Act to amend the Canadian Forces Members and Veterans Re-establishment and Compensation Act and to make consequential amendments to other Acts', 'Loi modifiant la Loi sur les mesures de réinsertion et d'indemnisation des militaires et vétérans des Forces canadiennes et d'autres lois en conséquence', '2016-03-24', 8166461);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Jim Hillyer', 71945, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Randy Hoback', 59148, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Mark Holland', 25508, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Anthony Housefather', 88558, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Carol Hughes', 31289, 'C-270', 'An Act respecting the establishment and award of a Defence of Canada Medal (1946-1989)', 'Loi prévoyant la création et l’attribution de la médaille de la défense du Canada (1946-1989)', '2016-05-10', 8196386);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Ahmed Hussen', 89020, 'C-227', 'An Act to amend the Department of Public Works and Government Services Act (community benefit)', 'Loi modifiant la Loi sur le ministère des Travaux publics et des Services gouvernementaux (retombées locales)', '2016-02-24', 8102366);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Gudie Hutchings', 88292, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Angelo Iacono', 71337, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Matt Jeneroux', 89167, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Gord Johns', 89263, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Georgina Jolibois', 89065, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Mélanie Joly', 88384, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Yvonne Jones', 13218, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Bernadette Jordan', 88340, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Majid Jowhari', 88929, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Peter Julian', 16399, 'C-263', 'An Act to amend the Income Tax Act (hearing impairment)', 'Loi modifiant la Loi de l’impôt sur le revenu (déficience auditive)', '2016-04-22', 8084584);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Darshan Singh Kang', 89144, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Pat Kelly', 89130, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Jason Kenney', 1302, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Peter Kent', 35699, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Iqra Khalid', 88849, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Kamal Khera', 88705, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Robert Gordon Kitchen', 89095, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Tom Kmiec', 89136, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Jenny Kwan', 89346, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Mike Lake', 35857, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'David Lametti', 88501, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Kevin Lamoureux', 30552, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Linda Lapointe', 88601, 'C-236', 'An Act to amend the Payment Card Networks Act (credit card acceptance fees)', 'Loi modifiant la Loi sur les réseaux de cartes de paiement (frais d’acceptation d’une carte de crédit)', '2016-02-25', 8117672);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Guy Lauzon', 25516, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Stéphane Lauzon', 88394, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Hélène Laverdière', 71434, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Denis Lebel', 38633, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Dominic LeBlanc', 1813, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Diane Lebouthillier', 88460, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Paul Lefebvre', 88973, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Kellie Leitch', 71786, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Denis Lemieux', 88446, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Andrew Leslie', 88894, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Michael Levitt', 89018, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Ron Liepert', 89139, 'C-229', 'An Act to amend the Criminal Code and the Corrections and Conditional Release Act and to make related and consequential amendments to other Acts (life sentences)', 'Loi modifiant le Code criminel et la Loi sur le système correctionnel et la mise en liberté sous condition et apportant des modifications connexes et corrélatives à d’autres lois (emprisonnement à perpétuité)', '2016-02-24', 8112948);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Joël Lightbound', 88532, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Ben Lobb', 35600, 'C-232', 'An Act to amend the Excise Act, 2001 (spirits)', 'Loi modifiant la Loi de 2001 sur l’accise (spiritueux)', '2016-02-25', 8112035);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Alaina Lockhart', 88357, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Wayne Long', 88368, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Lloyd Longfield', 88761, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Karen Ludwig', 88365, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Tom Lukiwski', 25520, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Lawrence MacAulay', 33, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Alistair MacGregor', 89269, 'C-252', 'An Act to amend the Navigation Protection Act (Shawnigan Lake)', 'Loi modifiant la Loi sur la protection de la navigation (lac Shawnigan)', '2016-03-10', 8136604);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Dave MacKenzie', 891, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Steven MacKinnon', 88468, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Larry Maguire', 7251, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Sheila Malcolmson', 89486, 'C-220', 'An Act to amend the Financial Administration Act (balanced representation)', 'Loi modifiant la Loi sur la gestion des finances publiques (représentation équilibrée)', '2016-02-16', 8069862);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'James Maloney', 88748, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Simon Marcil', 88544, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Brian Masse', 9137, 'C-221', 'An Act to amend the Criminal Code (sports betting)', 'Loi modifiant le Code criminel (paris sportifs)', '2016-02-17', 8092059);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Rémi Massé', 88397, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Irene Mathyssen', 764, 'C-260', 'An Act to amend the Canadian Forces Superannuation Act and the Royal Canadian Mounted Police Superannuation Act (deduction of disability pensions)', 'Loi modifiant la Loi sur la pension de retraite des Forces canadiennes et la Loi sur la pension de retraite de la Gendarmerie royale du Canada (déduction de la pension d’invalidité)', '2016-04-14', 8172639);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Bryan May', 71599, 'C-240', 'An Act to amend the Income Tax Act (tax credit — first aid)', 'Loi modifiant la Loi de l’impôt sur le revenu (crédit d’impôt — secourisme)', '2016-02-25', 8112051);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Elizabeth May', 2897, 'C-269', 'An Act to amend the Criminal Code and the Controlled Drugs and Substances Act (sentencing) and to make consequential amendments to another Act', 'Loi modifiant le Code criminel et la Loi réglementant certaines drogues et autres substances (détermination de la peine) et apportant des modifications corrélatives à une autre loi', '2016-05-05', 8175262);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'John McCallum', 1817, 'C-6', 'An Act to amend the Citizenship Act and to make consequential amendments to another Act', 'Loi modifiant la Loi sur la citoyenneté et une autre loi en conséquence', '2016-02-25', 8117654);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Kelly McCauley', 89179, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Phil McColeman', 35539, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Karen McCrimmon', 71602, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Ken McDonald', 88283, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'David McGuinty', 9486, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'John McKay', 957, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Catherine McKenna', 88892, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Ron McKinnon', 59293, 'C-224', 'An Act to amend the Controlled Drugs and Substances Act (assistance — drug overdose)', 'Loi modifiant la Loi réglementant certaines drogues et autres substances (aide lors de surdose)', '2016-02-22', 8108134);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Cathy McLeod', 59265, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Michael McLeod', 89374, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Alexandra Mendes', 58621, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Marco Mendicino', 88738, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'MaryAnn Mihychuk', 89037, 'C-4', 'An Act to amend the Canada Labour Code, the Parliamentary Employment and Staff Relations Act, the Public Service Labour Relations Act and the Income Tax Act', 'Loi modifiant le Code canadien du travail, la Loi sur les relations de travail au Parlement, la Loi sur les relations de travail dans la fonction publique et la Loi de l'impôt sur le revenu', '2016-01-28', 8073132);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Larry Miller', 25522, 'C-230', 'An Act to amend the Criminal Code (firearm — definition of variant)', 'Loi modifiant le Code criminel (arme à feu — définition de variante)', '2016-02-24', 8111356);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Marc Miller', 88660, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Maryam Monsef', 88922, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Christine Moore', 232, 'C-254', 'An Act to amend the Excise Tax Act (baby products)', 'Loi modifiant la Loi sur la taxe d’accise (produits pour bébés)', '2016-03-24', 8161840);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Bill Morneau', 88992, 'C-15', 'An Act to implement certain provisions of the budget tabled in Parliament on March 22, 2016 and other measures', 'Loi portant exécution de certaines dispositions du budget déposé au Parlement le 22 mars 2016 et mettant en oeuvre d'autres mesures', '2016-04-20', 8196581);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Bobby Morrissey', 88308, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Thomas Mulcair', 26684, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Joyce Murray', 35950, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Pierre Nantel', 71447, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Eva Nassif', 58806, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'John Nater', 88917, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Bob Nault', 709, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Rob Nicholson', 820, 'C-233', 'An Act respecting a national strategy for Alzheimer’s disease and other dementias', 'Loi concernant une stratégie nationale sur la maladie d’Alzheimer et d’autres démences', '2016-02-25', 8118650);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Alex Nuttall', 88679, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Deepak Obhrai', 1287, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Jennifer O'Connell', 88925, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Rob Oliphant', 58858, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'John Oliver', 88881, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Seamus O'Regan', 88299, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Erin O'Toole', 72773, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Robert-Falcon Ouellette', 89466, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Denis Paradis', 198, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Pierre Paul-Hus', 71454, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Monique Pauzé', 88595, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Joe Peschisolido', 1825, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Kyle Peterson', 71702, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Ginette Petitpas Taylor', 88364, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Jane Philpott', 88835, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Michel Picard', 71529, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Louis Plamondon', 413, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Pierre Poilievre', 25524, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Jean-Claude Poissant', 88493, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Anne Minh-Thu Quach', 71350, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Carla Qualtrough', 89272, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Lisa Raitt', 54325, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Tracey Ramsey', 88745, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Murray Rankin', 60078, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Yasmin Ratansi', 25449, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Alain Rayes', 88600, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Geoff Regan', 1760, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Scott Reid', 1827, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Michelle Rempel', 71902, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Blake Richards', 59235, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Jean Rioux', 88623, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Gerry Ritz', 1209, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Yves Robillard', 88617, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Pablo Rodriguez', 25451, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Sherry Romanado', 88521, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Anthony Rota', 25452, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Kim Rudd', 71718, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Dan Ruimy', 89304, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Don Rusnak', 88982, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Romeo Saganash', 71482, 'C-262', 'An Act to ensure that the laws of Canada are in harmony with the United Nations Declaration on the Rights of Indigenous Peoples', 'Loi visant à assurer l’harmonie des lois fédérales avec la Déclaration des Nations Unies sur les droits des peuples autochtones', '2016-04-21', 8160636);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Ruby Sahota', 88698, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Raj Saini', 88807, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Harjit S. Sajjan', 89497, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Darrell Samson', 88333, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Ramesh Sangha', 88692, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Brigitte Sansoucy', 53569, 'C-245', 'An Act concerning the development of a national poverty reduction strategy in Canada', 'Loi concernant l'élaboration d'une stratégie nationale sur la réduction de la pauvreté au Canada', '2016-02-26', 8122303);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Randeep Sarai', 89339, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Bob Saroya', 58878, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Francis Scarpaleggia', 25453, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Andrew Scheer', 25454, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Peter Schiefke', 88649, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Jamie Schmale', 88770, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Deb Schulte', 88799, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Marc Serré', 88874, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Judy Sgro', 1787, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Brenda Shanahan', 88442, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Terry Sheehan', 88944, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Martin Shields', 89109, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Bev Shipley', 31664, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Jati Sidhu', 89288, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Sonia Sidhu', 88703, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Gagan Sikand', 88858, 'C-247', 'An Act to amend the Criminal Code (passive detection device)', 'Loi modifiant le Code criminel (détecteur passif)', '2016-02-26', 8118649);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Scott Simms', 25456, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Amarjeet Sohi', 89163, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Robert Sopuck', 69488, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Francesco Sorbara', 88999, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Kevin Sorenson', 1832, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Sven Spengemann', 88852, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Bruce Stanton', 35724, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Gabriel Ste-Marie', 88485, 'C-222', 'An Act to amend the Income Tax Act (Canada-Barbados Income Tax Agreement)', 'Loi modifiant la Loi de l'impôt sur le revenu (Accord Canada-Barbade en matière d'impôt sur le revenu)', '2016-02-17', 8092276);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Wayne Stetski', 89281, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('True', 'Kennedy Stewart', 31701, 'C-217', 'An Act respecting the position and office of the Parliamentary Science Officer and to make consequential amendments to other Acts', 'Loi concernant le poste de directeur parlementaire des sciences et son bureau et apportant des modifications corrélatives à d’autres lois', '2016-02-04', 8076535);
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Mark Strahl', 71986, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Shannon Stubbs', 89198, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'David Sweet', 31715, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Marwan Tabbara', 88813, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Geng Tan', 88726, '', '', '', '', );
INSERT INTO members (existence, mp_name, mp_id, bill_number, descriptionEN, descriptionFR, dateIntroduced, legisinfoID)
VALUES ('N/A', 'Filomena Tassi', 88784, '', '', '', '', );
