module Riding_seed 
  def self.seed 
   Riding.create!(name: 'Abbotsford', special_riding_id: '898', special_mp_id: '35904')
   Riding.create!(name: 'Abitibi—Baie-James—Nunavik—Eeyou', special_riding_id: '637', special_mp_id: '71482')
   Riding.create!(name: 'Abitibi—Témiscamingue', special_riding_id: '638', special_mp_id: '232')
   Riding.create!(name: 'Acadie—Bathurst', special_riding_id: '627', special_mp_id: '88350')
   Riding.create!(name: 'Ahuntsic-Cartierville', special_riding_id: '639', special_mp_id: '88384')
   Riding.create!(name: 'Ajax', special_riding_id: '715', special_mp_id: '25508')
   Riding.create!(name: 'Alfred-Pellan', special_riding_id: '640', special_mp_id: '71337')
   Riding.create!(name: 'Algoma—Manitoulin—Kapuskasing', special_riding_id: '716', special_mp_id: '31289')
   Riding.create!(name: 'Argenteuil—La Petite-Nation', special_riding_id: '641', special_mp_id: '88394')
   Riding.create!(name: 'Aurora—Oak Ridges—Richmond Hill', special_riding_id: '717', special_mp_id: '88671')
   Riding.create!(name: 'Avalon', special_riding_id: '605', special_mp_id: '88283')
   Riding.create!(name: 'Avignon—La Mitis—Matane—Matapédia', special_riding_id: '642', special_mp_id: '88397')
   Riding.create!(name: 'Banff—Airdrie', special_riding_id: '864', special_mp_id: '59235')
   Riding.create!(name: 'Barrie—Innisfil', special_riding_id: '718', special_mp_id: '88674')
   Riding.create!(name: 'Barrie—Springwater—Oro-Medonte', special_riding_id: '719', special_mp_id: '88679')
   Riding.create!(name: 'Battle River—Crowfoot', special_riding_id: '865', special_mp_id: '1832')
   Riding.create!(name: 'Battlefords—Lloydminster', special_riding_id: '850', special_mp_id: '1209')
   Riding.create!(name: 'Bay of Quinte', special_riding_id: '720', special_mp_id: '88683')
   Riding.create!(name: 'Beaches—East York', special_riding_id: '721', special_mp_id: '88687')
   Riding.create!(name: 'Beauce', special_riding_id: '643', special_mp_id: '35309')
   Riding.create!(name: 'Beauport—Côte-de-Beaupré—Île d\'Orléans—Charlevoix', special_riding_id: '656', special_mp_id: '35320')
   Riding.create!(name: 'Beauport—Limoilou', special_riding_id: '644', special_mp_id: '88404')
   Riding.create!(name: 'Beauséjour', special_riding_id: '628', special_mp_id: '1813')
   Riding.create!(name: 'Bécancour—Nicolet—Saurel', special_riding_id: '645', special_mp_id: '413')
   Riding.create!(name: 'Bellechasse—Les Etchemins—Lévis', special_riding_id: '646', special_mp_id: '35389')
   Riding.create!(name: 'Beloeil—Chambly', special_riding_id: '647', special_mp_id: '71368')
   Riding.create!(name: 'Berthier—Maskinongé', special_riding_id: '648', special_mp_id: '71357')
   Riding.create!(name: 'Bonavista—Burin—Trinity', special_riding_id: '606', special_mp_id: '58519')
   Riding.create!(name: 'Bourassa', special_riding_id: '651', special_mp_id: '84660')
   Riding.create!(name: 'Bow River', special_riding_id: '866', special_mp_id: '89109')
   Riding.create!(name: 'Brampton Centre', special_riding_id: '722', special_mp_id: '88692')
   Riding.create!(name: 'Brampton East', special_riding_id: '723', special_mp_id: '88694')
   Riding.create!(name: 'Brampton North', special_riding_id: '724', special_mp_id: '88698')
   Riding.create!(name: 'Brampton South', special_riding_id: '725', special_mp_id: '88703')
   Riding.create!(name: 'Brampton West', special_riding_id: '726', special_mp_id: '88705')
   Riding.create!(name: 'Brandon—Souris', special_riding_id: '836', special_mp_id: '7251')
   Riding.create!(name: 'Brantford—Brant', special_riding_id: '727', special_mp_id: '35539')
   Riding.create!(name: 'Brome—Missisquoi', special_riding_id: '652', special_mp_id: '198')
   Riding.create!(name: 'Brossard—Saint-Lambert', special_riding_id: '653', special_mp_id: '58621')
   Riding.create!(name: 'Bruce—Grey—Owen Sound', special_riding_id: '728', special_mp_id: '25522')
   Riding.create!(name: 'Burlington', special_riding_id: '729', special_mp_id: '88715')
   Riding.create!(name: 'Burnaby North—Seymour', special_riding_id: '899', special_mp_id: '89236')
   Riding.create!(name: 'Burnaby South', special_riding_id: '900', special_mp_id: '31701')
   Riding.create!(name: 'Calgary Centre', special_riding_id: '867', special_mp_id: '89111')
   Riding.create!(name: 'Calgary Confederation', special_riding_id: '868', special_mp_id: '89116')
   Riding.create!(name: 'Calgary Forest Lawn', special_riding_id: '869', special_mp_id: '1287')
   Riding.create!(name: 'Calgary Heritage', special_riding_id: '870', special_mp_id: '1733')
   Riding.create!(name: 'Calgary Midnapore', special_riding_id: '871', special_mp_id: '1302')
   Riding.create!(name: 'Calgary Nose Hill', special_riding_id: '872', special_mp_id: '71902')
   Riding.create!(name: 'Calgary Rocky Ridge', special_riding_id: '873', special_mp_id: '89130')
   Riding.create!(name: 'Calgary Shepard', special_riding_id: '874', special_mp_id: '89136')
   Riding.create!(name: 'Calgary Signal Hill', special_riding_id: '875', special_mp_id: '89139')
   Riding.create!(name: 'Calgary Skyview', special_riding_id: '876', special_mp_id: '89144')
   Riding.create!(name: 'Cambridge', special_riding_id: '730', special_mp_id: '71599')
   Riding.create!(name: 'Cape Breton—Canso', special_riding_id: '616', special_mp_id: '1804')
   Riding.create!(name: 'Cardigan', special_riding_id: '612', special_mp_id: '33')
   Riding.create!(name: 'Cariboo—Prince George', special_riding_id: '901', special_mp_id: '89249')
   Riding.create!(name: 'Carleton', special_riding_id: '802', special_mp_id: '25524')
   Riding.create!(name: 'Carlton Trail—Eagle Creek', special_riding_id: '853', special_mp_id: '59156')
   Riding.create!(name: 'Central Nova', special_riding_id: '617', special_mp_id: '88316')
   Riding.create!(name: 'Central Okanagan—Similkameen—Nicola', special_riding_id: '902', special_mp_id: '72029')
   Riding.create!(name: 'Charlesbourg—Haute-Saint-Charles', special_riding_id: '655', special_mp_id: '71454')
   Riding.create!(name: 'Charleswood—St. James—Assiniboia—Headingley', special_riding_id: '837', special_mp_id: '89027')
   Riding.create!(name: 'Charlottetown', special_riding_id: '613', special_mp_id: '71270')
   Riding.create!(name: 'Châteauguay—Lacolle', special_riding_id: '657', special_mp_id: '88442')
   Riding.create!(name: 'Chatham-Kent—Leamington', special_riding_id: '731', special_mp_id: '31765')
   Riding.create!(name: 'Chicoutimi—Le Fjord', special_riding_id: '658', special_mp_id: '88446')
   Riding.create!(name: 'Chilliwack—Hope', special_riding_id: '903', special_mp_id: '71986')
   Riding.create!(name: 'Churchill—Keewatinook Aski', special_riding_id: '838', special_mp_id: '36037')
   Riding.create!(name: 'Cloverdale—Langley City', special_riding_id: '904', special_mp_id: '89258')
   Riding.create!(name: 'Coast of Bays—Central—Notre Dame', special_riding_id: '607', special_mp_id: '25456')
   Riding.create!(name: 'Compton—Stanstead', special_riding_id: '659', special_mp_id: '88449')
   Riding.create!(name: 'Coquitlam—Port Coquitlam', special_riding_id: '905', special_mp_id: '59293')
   Riding.create!(name: 'Courtenay—Alberni', special_riding_id: '906', special_mp_id: '89263')
   Riding.create!(name: 'Cowichan—Malahat—Langford', special_riding_id: '907', special_mp_id: '89269')
   Riding.create!(name: 'Cumberland—Colchester', special_riding_id: '618', special_mp_id: '51')
   Riding.create!(name: 'Cypress Hills—Grasslands', special_riding_id: '851', special_mp_id: '1795')
   Riding.create!(name: 'Dartmouth—Cole Harbour', special_riding_id: '619', special_mp_id: '88323')
   Riding.create!(name: 'Dauphin—Swan River—Neepawa', special_riding_id: '839', special_mp_id: '69488')
   Riding.create!(name: 'Davenport', special_riding_id: '732', special_mp_id: '88721')
   Riding.create!(name: 'Delta', special_riding_id: '908', special_mp_id: '89272')
   Riding.create!(name: 'Desnethé—Missinippi—Churchill River', special_riding_id: '852', special_mp_id: '89065')
   Riding.create!(name: 'Don Valley East', special_riding_id: '733', special_mp_id: '25449')
   Riding.create!(name: 'Don Valley North', special_riding_id: '734', special_mp_id: '88726')
   Riding.create!(name: 'Don Valley West', special_riding_id: '735', special_mp_id: '58858')
   Riding.create!(name: 'Dorval—Lachine—LaSalle', special_riding_id: '660', special_mp_id: '88453')
   Riding.create!(name: 'Drummond', special_riding_id: '661', special_mp_id: '35351')
   Riding.create!(name: 'Dufferin—Caledon', special_riding_id: '736', special_mp_id: '25461')
   Riding.create!(name: 'Durham', special_riding_id: '737', special_mp_id: '72773')
   Riding.create!(name: 'Edmonton Centre', special_riding_id: '877', special_mp_id: '89147')
   Riding.create!(name: 'Edmonton Griesbach', special_riding_id: '878', special_mp_id: '89150')
   Riding.create!(name: 'Edmonton Manning', special_riding_id: '879', special_mp_id: '89156')
   Riding.create!(name: 'Edmonton Mill Woods', special_riding_id: '880', special_mp_id: '89163')
   Riding.create!(name: 'Edmonton Riverbend', special_riding_id: '881', special_mp_id: '89167')
   Riding.create!(name: 'Edmonton Strathcona', special_riding_id: '882', special_mp_id: '35873')
   Riding.create!(name: 'Edmonton West', special_riding_id: '883', special_mp_id: '89179')
   Riding.create!(name: 'Edmonton—Wetaskiwin', special_riding_id: '884', special_mp_id: '35857')
   Riding.create!(name: 'Eglinton—Lawrence', special_riding_id: '738', special_mp_id: '88738')
   Riding.create!(name: 'Egmont', special_riding_id: '614', special_mp_id: '88308')
   Riding.create!(name: 'Elgin—Middlesex—London', special_riding_id: '739', special_mp_id: '88742')
   Riding.create!(name: 'Elmwood—Transcona', special_riding_id: '840', special_mp_id: '89032')
   Riding.create!(name: 'Esquimalt—Saanich—Sooke', special_riding_id: '923', special_mp_id: '71995')
   Riding.create!(name: 'Essex', special_riding_id: '740', special_mp_id: '88745')
   Riding.create!(name: 'Etobicoke Centre', special_riding_id: '741', special_mp_id: '25468')
   Riding.create!(name: 'Etobicoke North', special_riding_id: '743', special_mp_id: '58877')
   Riding.create!(name: 'Etobicoke—Lakeshore', special_riding_id: '742', special_mp_id: '88748')
   Riding.create!(name: 'Flamborough—Glanbrook', special_riding_id: '744', special_mp_id: '31715')
   Riding.create!(name: 'Fleetwood—Port Kells', special_riding_id: '909', special_mp_id: '89274')
   Riding.create!(name: 'Foothills', special_riding_id: '885', special_mp_id: '86261')
   Riding.create!(name: 'Fort McMurray—Cold Lake', special_riding_id: '886', special_mp_id: '86260')
   Riding.create!(name: 'Fredericton', special_riding_id: '629', special_mp_id: '88355')
   Riding.create!(name: 'Fundy Royal', special_riding_id: '630', special_mp_id: '88357')
   Riding.create!(name: 'Gaspésie—Les Îles-de-la-Madeleine', special_riding_id: '662', special_mp_id: '88460')
   Riding.create!(name: 'Gatineau', special_riding_id: '663', special_mp_id: '88468')
   Riding.create!(name: 'Glengarry—Prescott—Russell', special_riding_id: '745', special_mp_id: '88756')
   Riding.create!(name: 'Grande Prairie—Mackenzie', special_riding_id: '887', special_mp_id: '35886')
   Riding.create!(name: 'Guelph', special_riding_id: '746', special_mp_id: '88761')
   Riding.create!(name: 'Haldimand—Norfolk', special_riding_id: '747', special_mp_id: '25501')
   Riding.create!(name: 'Haliburton—Kawartha Lakes—Brock', special_riding_id: '748', special_mp_id: '88770')
   Riding.create!(name: 'Halifax', special_riding_id: '620', special_mp_id: '88325')
   Riding.create!(name: 'Halifax West', special_riding_id: '621', special_mp_id: '1760')
   Riding.create!(name: 'Hamilton Centre', special_riding_id: '749', special_mp_id: '25489')
   Riding.create!(name: 'Hamilton East—Stoney Creek', special_riding_id: '750', special_mp_id: '88775')
   Riding.create!(name: 'Hamilton Mountain', special_riding_id: '751', special_mp_id: '88780')
   Riding.create!(name: 'Hamilton West—Ancaster—Dundas', special_riding_id: '752', special_mp_id: '88784')
   Riding.create!(name: 'Hastings—Lennox and Addington', special_riding_id: '753', special_mp_id: '88786')
   Riding.create!(name: 'Hochelaga', special_riding_id: '664', special_mp_id: '71395')
   Riding.create!(name: 'Honoré-Mercier', special_riding_id: '665', special_mp_id: '25451')
   Riding.create!(name: 'Hull—Aylmer', special_riding_id: '666', special_mp_id: '88478')
   Riding.create!(name: 'Humber River—Black Creek', special_riding_id: '835', special_mp_id: '1787')
   Riding.create!(name: 'Huron—Bruce', special_riding_id: '754', special_mp_id: '35600')
   Riding.create!(name: 'Joliette', special_riding_id: '667', special_mp_id: '88485')
   Riding.create!(name: 'Jonquière', special_riding_id: '668', special_mp_id: '88488')
   Riding.create!(name: 'Kamloops—Thompson—Cariboo', special_riding_id: '910', special_mp_id: '59265')
   Riding.create!(name: 'Kanata—Carleton', special_riding_id: '755', special_mp_id: '71602')
   Riding.create!(name: 'Kelowna—Lake Country', special_riding_id: '911', special_mp_id: '89279')
   Riding.create!(name: 'Kenora', special_riding_id: '756', special_mp_id: '709')
   Riding.create!(name: 'Kildonan—St. Paul', special_riding_id: '841', special_mp_id: '89037')
   Riding.create!(name: 'Kings—Hants', special_riding_id: '622', special_mp_id: '74')
   Riding.create!(name: 'Kingston and the Islands', special_riding_id: '758', special_mp_id: '88802')
   Riding.create!(name: 'King—Vaughan', special_riding_id: '757', special_mp_id: '88799')
   Riding.create!(name: 'Kitchener Centre', special_riding_id: '759', special_mp_id: '88807')
   Riding.create!(name: 'Kitchener South—Hespeler', special_riding_id: '761', special_mp_id: '88813')
   Riding.create!(name: 'Kitchener—Conestoga', special_riding_id: '760', special_mp_id: '35607')
   Riding.create!(name: 'Kootenay—Columbia', special_riding_id: '912', special_mp_id: '89281')
   Riding.create!(name: 'La Pointe-de-l\'Île', special_riding_id: '669', special_mp_id: '376')
   Riding.create!(name: 'La Prairie', special_riding_id: '670', special_mp_id: '88493')
   Riding.create!(name: 'Labrador', special_riding_id: '608', special_mp_id: '13218')
   Riding.create!(name: 'Lac-Saint-Jean', special_riding_id: '671', special_mp_id: '38633')
   Riding.create!(name: 'Lac-Saint-Louis', special_riding_id: '672', special_mp_id: '25453')
   Riding.create!(name: 'Lakeland', special_riding_id: '888', special_mp_id: '89198')
   Riding.create!(name: 'Lambton—Kent—Middlesex', special_riding_id: '762', special_mp_id: '31664')
   Riding.create!(name: 'Lanark—Frontenac—Kingston', special_riding_id: '763', special_mp_id: '1827')
   Riding.create!(name: 'Langley—Aldergrove', special_riding_id: '913', special_mp_id: '25467')
   Riding.create!(name: 'LaSalle—Émard—Verdun', special_riding_id: '673', special_mp_id: '88501')
   Riding.create!(name: 'Laurentides—Labelle', special_riding_id: '674', special_mp_id: '88504')
   Riding.create!(name: 'Laurier—Sainte-Marie', special_riding_id: '675', special_mp_id: '71434')
   Riding.create!(name: 'Laval—Les Îles', special_riding_id: '676', special_mp_id: '88515')
   Riding.create!(name: 'Leeds—Grenville—Thousand Islands and Rideau Lakes', special_riding_id: '764', special_mp_id: '25483')
   Riding.create!(name: 'Lethbridge', special_riding_id: '889', special_mp_id: '89200')
   Riding.create!(name: 'Lévis—Lotbinière', special_riding_id: '678', special_mp_id: '35397')
   Riding.create!(name: 'London North Centre', special_riding_id: '766', special_mp_id: '88827')
   Riding.create!(name: 'London West', special_riding_id: '767', special_mp_id: '88832')
   Riding.create!(name: 'London—Fanshawe', special_riding_id: '765', special_mp_id: '764')
   Riding.create!(name: 'Long Range Mountains', special_riding_id: '609', special_mp_id: '88292')
   Riding.create!(name: 'Longueuil—Charles-LeMoyne', special_riding_id: '677', special_mp_id: '88521')
   Riding.create!(name: 'Longueuil—Saint-Hubert', special_riding_id: '679', special_mp_id: '71447')
   Riding.create!(name: 'Louis-Hébert', special_riding_id: '680', special_mp_id: '88532')
   Riding.create!(name: 'Louis-Saint-Laurent', special_riding_id: '681', special_mp_id: '88535')
   Riding.create!(name: 'Madawaska—Restigouche', special_riding_id: '631', special_mp_id: '89383')
   Riding.create!(name: 'Malpeque', special_riding_id: '615', special_mp_id: '43')
   Riding.create!(name: 'Manicouagan', special_riding_id: '682', special_mp_id: '88538')
   Riding.create!(name: 'Marc-Aurèle-Fortin', special_riding_id: '701', special_mp_id: '88617')
   Riding.create!(name: 'Markham—Stouffville', special_riding_id: '768', special_mp_id: '88835')
   Riding.create!(name: 'Markham—Thornhill', special_riding_id: '769', special_mp_id: '1817')
   Riding.create!(name: 'Markham—Unionville', special_riding_id: '770', special_mp_id: '58878')
   Riding.create!(name: 'Medicine Hat—Cardston—Warner', special_riding_id: '890', special_mp_id: 'N/A')
   Riding.create!(name: 'Mégantic—L\'Érable', special_riding_id: '683', special_mp_id: '88541')
   Riding.create!(name: 'Milton', special_riding_id: '771', special_mp_id: '54325')
   Riding.create!(name: 'Mirabel', special_riding_id: '684', special_mp_id: '88544')
   Riding.create!(name: 'Miramichi—Grand Lake', special_riding_id: '632', special_mp_id: '88360')
   Riding.create!(name: 'Mission—Matsqui—Fraser Canyon', special_riding_id: '914', special_mp_id: '89288')
   Riding.create!(name: 'Mississauga Centre', special_riding_id: '772', special_mp_id: '89535')
   Riding.create!(name: 'Mississauga East—Cooksville', special_riding_id: '773', special_mp_id: '71692')
   Riding.create!(name: 'Mississauga—Erin Mills', special_riding_id: '774', special_mp_id: '88849')
   Riding.create!(name: 'Mississauga—Lakeshore', special_riding_id: '775', special_mp_id: '88852')
   Riding.create!(name: 'Mississauga—Malton', special_riding_id: '776', special_mp_id: '25471')
   Riding.create!(name: 'Mississauga—Streetsville', special_riding_id: '777', special_mp_id: '88858')
   Riding.create!(name: 'Moncton—Riverview—Dieppe', special_riding_id: '633', special_mp_id: '88364')
   Riding.create!(name: 'Montarville', special_riding_id: '685', special_mp_id: '71529')
   Riding.create!(name: 'Montcalm', special_riding_id: '686', special_mp_id: '88552')
   Riding.create!(name: 'Montmagny—L\'Islet—Kamouraska—Rivière-du-Loup', special_riding_id: '687', special_mp_id: '63908')
   Riding.create!(name: 'Moose Jaw—Lake Centre—Lanigan', special_riding_id: '854', special_mp_id: '25520')
   Riding.create!(name: 'Mount Royal', special_riding_id: '688', special_mp_id: '88558')
   Riding.create!(name: 'Nanaimo—Ladysmith', special_riding_id: '915', special_mp_id: '89486')
   Riding.create!(name: 'Nepean', special_riding_id: '778', special_mp_id: '88860')
   Riding.create!(name: 'New Brunswick Southwest', special_riding_id: '634', special_mp_id: '88365')
   Riding.create!(name: 'New Westminster—Burnaby', special_riding_id: '916', special_mp_id: '16399')
   Riding.create!(name: 'Newmarket—Aurora', special_riding_id: '779', special_mp_id: '71702')
   Riding.create!(name: 'Niagara Centre', special_riding_id: '780', special_mp_id: '88867')
   Riding.create!(name: 'Niagara Falls', special_riding_id: '781', special_mp_id: '820')
   Riding.create!(name: 'Niagara West', special_riding_id: '782', special_mp_id: '25446')
   Riding.create!(name: 'Nickel Belt', special_riding_id: '783', special_mp_id: '88874')
   Riding.create!(name: 'Nipissing—Timiskaming', special_riding_id: '784', special_mp_id: '25452')
   Riding.create!(name: 'North Island—Powell River', special_riding_id: '934', special_mp_id: '89354')
   Riding.create!(name: 'North Okanagan—Shuswap', special_riding_id: '917', special_mp_id: '89294')
   Riding.create!(name: 'North Vancouver', special_riding_id: '918', special_mp_id: '89300')
   Riding.create!(name: 'Northumberland—Peterborough South', special_riding_id: '785', special_mp_id: '71718')
   Riding.create!(name: 'Northwest Territories', special_riding_id: '941', special_mp_id: '89374')
   Riding.create!(name: 'Notre-Dame-de-Grâce—Westmount', special_riding_id: '689', special_mp_id: '10524')
   Riding.create!(name: 'Nunavut', special_riding_id: '942', special_mp_id: '1665')
   Riding.create!(name: 'Oakville', special_riding_id: '786', special_mp_id: '88881')
   Riding.create!(name: 'Oakville North—Burlington', special_riding_id: '787', special_mp_id: '88884')
   Riding.create!(name: 'Orléans', special_riding_id: '790', special_mp_id: '88894')
   Riding.create!(name: 'Oshawa', special_riding_id: '788', special_mp_id: '25486')
   Riding.create!(name: 'Ottawa Centre', special_riding_id: '789', special_mp_id: '88892')
   Riding.create!(name: 'Ottawa South', special_riding_id: '791', special_mp_id: '9486')
   Riding.create!(name: 'Ottawa West—Nepean', special_riding_id: '793', special_mp_id: '71738')
   Riding.create!(name: 'Ottawa—Vanier', special_riding_id: '792', special_mp_id: '873')
   Riding.create!(name: 'Outremont', special_riding_id: '690', special_mp_id: '26684')
   Riding.create!(name: 'Oxford', special_riding_id: '794', special_mp_id: '891')
   Riding.create!(name: 'Papineau', special_riding_id: '691', special_mp_id: '58733')
   Riding.create!(name: 'Parkdale—High Park', special_riding_id: '795', special_mp_id: '88910')
   Riding.create!(name: 'Parry Sound—Muskoka', special_riding_id: '796', special_mp_id: '15975')
   Riding.create!(name: 'Peace River—Westlock', special_riding_id: '891', special_mp_id: '89211')
   Riding.create!(name: 'Perth—Wellington', special_riding_id: '797', special_mp_id: '88917')
   Riding.create!(name: 'Peterborough—Kawartha', special_riding_id: '798', special_mp_id: '88922')
   Riding.create!(name: 'Pickering—Uxbridge', special_riding_id: '799', special_mp_id: '88925')
   Riding.create!(name: 'Pierre-Boucher—Les Patriotes—Verchères', special_riding_id: '650', special_mp_id: '88422')
   Riding.create!(name: 'Pierrefonds—Dollard', special_riding_id: '692', special_mp_id: '88578')
   Riding.create!(name: 'Pitt Meadows—Maple Ridge', special_riding_id: '919', special_mp_id: '89304')
   Riding.create!(name: 'Pontiac', special_riding_id: '693', special_mp_id: '89527')
   Riding.create!(name: 'Port Moody—Coquitlam', special_riding_id: '920', special_mp_id: '63592')
   Riding.create!(name: 'Portage—Lisgar', special_riding_id: '842', special_mp_id: '59110')
   Riding.create!(name: 'Portneuf—Jacques-Cartier', special_riding_id: '694', special_mp_id: '89407')
   Riding.create!(name: 'Prince Albert', special_riding_id: '855', special_mp_id: '59148')
   Riding.create!(name: 'Prince George—Peace River—Northern Rockies', special_riding_id: '921', special_mp_id: '72035')
   Riding.create!(name: 'Provencher', special_riding_id: '843', special_mp_id: '84672')
   Riding.create!(name: 'Québec', special_riding_id: '695', special_mp_id: '89408')
   Riding.create!(name: 'Red Deer—Lacombe', special_riding_id: '893', special_mp_id: '35897')
   Riding.create!(name: 'Red Deer—Mountain View', special_riding_id: '892', special_mp_id: '59226')
   Riding.create!(name: 'Regina—Lewvan', special_riding_id: '856', special_mp_id: '31796')
   Riding.create!(name: 'Regina—Qu\'Appelle', special_riding_id: '857', special_mp_id: '25454')
   Riding.create!(name: 'Regina—Wascana', special_riding_id: '858', special_mp_id: '1265')
   Riding.create!(name: 'Renfrew—Nipissing—Pembroke', special_riding_id: '800', special_mp_id: '1809')
   Riding.create!(name: 'Repentigny', special_riding_id: '696', special_mp_id: '88595')
   Riding.create!(name: 'Richmond Centre', special_riding_id: '922', special_mp_id: '30812')
   Riding.create!(name: 'Richmond Hill', special_riding_id: '801', special_mp_id: '88929')
   Riding.create!(name: 'Richmond—Arthabaska', special_riding_id: '697', special_mp_id: '88600')
   Riding.create!(name: 'Rimouski-Neigette—Témiscouata—Les Basques', special_riding_id: '654', special_mp_id: '23915')
   Riding.create!(name: 'Rivière-des-Mille-Îles', special_riding_id: '698', special_mp_id: '88601')
   Riding.create!(name: 'Rivière-du-Nord', special_riding_id: '699', special_mp_id: '88605')
   Riding.create!(name: 'Rosemont—La Petite-Patrie', special_riding_id: '700', special_mp_id: '58775')
   Riding.create!(name: 'Saanich—Gulf Islands', special_riding_id: '924', special_mp_id: '2897')
   Riding.create!(name: 'Sackville—Preston—Chezzetcook', special_riding_id: '623', special_mp_id: '88333')
   Riding.create!(name: 'Saint Boniface—Saint Vital', special_riding_id: '844', special_mp_id: '89045')
   Riding.create!(name: 'Saint John—Rothesay', special_riding_id: '635', special_mp_id: '88368')
   Riding.create!(name: 'Saint-Hyacinthe—Bagot', special_riding_id: '702', special_mp_id: '53569')
   Riding.create!(name: 'Saint-Jean', special_riding_id: '703', special_mp_id: '88623')
   Riding.create!(name: 'Saint-Laurent', special_riding_id: '704', special_mp_id: '460')
   Riding.create!(name: 'Saint-Léonard—Saint-Michel', special_riding_id: '705', special_mp_id: '88627')
   Riding.create!(name: 'Saint-Maurice—Champlain', special_riding_id: '706', special_mp_id: '88633')
   Riding.create!(name: 'Salaberry—Suroît', special_riding_id: '707', special_mp_id: '71350')
   Riding.create!(name: 'Sarnia—Lambton', special_riding_id: '805', special_mp_id: '88938')
   Riding.create!(name: 'Saskatoon West', special_riding_id: '861', special_mp_id: '89090')
   Riding.create!(name: 'Saskatoon—Grasswood', special_riding_id: '859', special_mp_id: '89084')
   Riding.create!(name: 'Saskatoon—University', special_riding_id: '860', special_mp_id: '25462')
   Riding.create!(name: 'Sault Ste. Marie', special_riding_id: '806', special_mp_id: '88944')
   Riding.create!(name: 'Scarborough Centre', special_riding_id: '808', special_mp_id: '88950')
   Riding.create!(name: 'Scarborough North', special_riding_id: '810', special_mp_id: '88953')
   Riding.create!(name: 'Scarborough Southwest', special_riding_id: '812', special_mp_id: '88961')
   Riding.create!(name: 'Scarborough—Agincourt', special_riding_id: '807', special_mp_id: '86249')
   Riding.create!(name: 'Scarborough—Guildwood', special_riding_id: '809', special_mp_id: '957')
   Riding.create!(name: 'Scarborough—Rouge Park', special_riding_id: '811', special_mp_id: '89449')
   Riding.create!(name: 'Selkirk—Interlake—Eastman', special_riding_id: '845', special_mp_id: '25475')
   Riding.create!(name: 'Shefford', special_riding_id: '708', special_mp_id: '58707')
   Riding.create!(name: 'Sherbrooke', special_riding_id: '709', special_mp_id: '71553')
   Riding.create!(name: 'Sherwood Park—Fort Saskatchewan', special_riding_id: '895', special_mp_id: '89226')
   Riding.create!(name: 'Simcoe North', special_riding_id: '814', special_mp_id: '35724')
   Riding.create!(name: 'Simcoe—Grey', special_riding_id: '813', special_mp_id: '71786')
   Riding.create!(name: 'Skeena—Bulkley Valley', special_riding_id: '925', special_mp_id: '25493')
   Riding.create!(name: 'Souris—Moose Mountain', special_riding_id: '862', special_mp_id: '89095')
   Riding.create!(name: 'South Okanagan—West Kootenay', special_riding_id: '926', special_mp_id: '89327')
   Riding.create!(name: 'South Shore—St. Margarets', special_riding_id: '624', special_mp_id: '88340')
   Riding.create!(name: 'South Surrey—White Rock', special_riding_id: '927', special_mp_id: '89333')
   Riding.create!(name: 'Spadina—Fort York', special_riding_id: '815', special_mp_id: '54434')
   Riding.create!(name: 'St. Albert—Edmonton', special_riding_id: '894', special_mp_id: '89219')
   Riding.create!(name: 'St. Catharines', special_riding_id: '803', special_mp_id: '88934')
   Riding.create!(name: 'St. John\'s East', special_riding_id: '610', special_mp_id: '88296')
   Riding.create!(name: 'St. John\'s South—Mount Pearl', special_riding_id: '611', special_mp_id: '88299')
   Riding.create!(name: 'Steveston—Richmond East', special_riding_id: '928', special_mp_id: '1825')
   Riding.create!(name: 'Stormont—Dundas—South Glengarry', special_riding_id: '816', special_mp_id: '25516')
   Riding.create!(name: 'Sturgeon River—Parkland', special_riding_id: '896', special_mp_id: '25447')
   Riding.create!(name: 'Sudbury', special_riding_id: '817', special_mp_id: '88973')
   Riding.create!(name: 'Surrey Centre', special_riding_id: '929', special_mp_id: '89339')
   Riding.create!(name: 'Surrey—Newton', special_riding_id: '930', special_mp_id: '31098')
   Riding.create!(name: 'Sydney—Victoria', special_riding_id: '625', special_mp_id: '1806')
   Riding.create!(name: 'Terrebonne', special_riding_id: '711', special_mp_id: '88651')
   Riding.create!(name: 'Thérèse-De Blainville', special_riding_id: '649', special_mp_id: '88419')
   Riding.create!(name: 'Thornhill', special_riding_id: '818', special_mp_id: '35699')
   Riding.create!(name: 'Thunder Bay—Rainy River', special_riding_id: '819', special_mp_id: '88982')
   Riding.create!(name: 'Thunder Bay—Superior North', special_riding_id: '820', special_mp_id: '88984')
   Riding.create!(name: 'Timmins—James Bay', special_riding_id: '821', special_mp_id: '25470')
   Riding.create!(name: 'Tobique—Mactaquac', special_riding_id: '636', special_mp_id: '88370')
   Riding.create!(name: 'Toronto Centre', special_riding_id: '822', special_mp_id: '88992')
   Riding.create!(name: 'Toronto—Danforth', special_riding_id: '823', special_mp_id: '88994')
   Riding.create!(name: 'Toronto—St. Paul\'s', special_riding_id: '804', special_mp_id: '992')
   Riding.create!(name: 'Trois-Rivières', special_riding_id: '712', special_mp_id: '71560')
   Riding.create!(name: 'University—Rosedale', special_riding_id: '824', special_mp_id: '84665')
   Riding.create!(name: 'Vancouver Centre', special_riding_id: '931', special_mp_id: '1589')
   Riding.create!(name: 'Vancouver East', special_riding_id: '932', special_mp_id: '89346')
   Riding.create!(name: 'Vancouver Granville', special_riding_id: '933', special_mp_id: '89494')
   Riding.create!(name: 'Vancouver Kingsway', special_riding_id: '935', special_mp_id: '59325')
   Riding.create!(name: 'Vancouver Quadra', special_riding_id: '936', special_mp_id: '35950')
   Riding.create!(name: 'Vancouver South', special_riding_id: '937', special_mp_id: '89497')
   Riding.create!(name: 'Vaudreuil—Soulanges', special_riding_id: '710', special_mp_id: '88649')
   Riding.create!(name: 'Vaughan—Woodbridge', special_riding_id: '825', special_mp_id: '88999')
   Riding.create!(name: 'Victoria', special_riding_id: '938', special_mp_id: '60078')
   Riding.create!(name: 'Ville-Marie—Le Sud-Ouest—Île-des-Soeurs', special_riding_id: '713', special_mp_id: '88660')
   Riding.create!(name: 'Vimy', special_riding_id: '714', special_mp_id: '58806')
   Riding.create!(name: 'Waterloo', special_riding_id: '826', special_mp_id: '89000')
   Riding.create!(name: 'Wellington—Halton Hills', special_riding_id: '827', special_mp_id: '25488')
   Riding.create!(name: 'West Nova', special_riding_id: '626', special_mp_id: '88346')
   Riding.create!(name: 'West Vancouver—Sunshine Coast—Sea to Sky Country', special_riding_id: '939', special_mp_id: '89370')
   Riding.create!(name: 'Whitby', special_riding_id: '828', special_mp_id: '86786')
   Riding.create!(name: 'Willowdale', special_riding_id: '829', special_mp_id: '89010')
   Riding.create!(name: 'Windsor West', special_riding_id: '831', special_mp_id: '9137')
   Riding.create!(name: 'Windsor—Tecumseh', special_riding_id: '830', special_mp_id: '89012')
   Riding.create!(name: 'Winnipeg Centre', special_riding_id: '846', special_mp_id: '89466')
   Riding.create!(name: 'Winnipeg North', special_riding_id: '847', special_mp_id: '30552')
   Riding.create!(name: 'Winnipeg South', special_riding_id: '848', special_mp_id: '31119')
   Riding.create!(name: 'Winnipeg South Centre', special_riding_id: '849', special_mp_id: '89059')
   Riding.create!(name: 'Yellowhead', special_riding_id: '897', special_mp_id: '48292')
   Riding.create!(name: 'York Centre', special_riding_id: '832', special_mp_id: '89018')
   Riding.create!(name: 'York South—Weston', special_riding_id: '834', special_mp_id: '89020')
   Riding.create!(name: 'York—Simcoe', special_riding_id: '833', special_mp_id: '25465')
   Riding.create!(name: 'Yorkton—Melville', special_riding_id: '863', special_mp_id: '89098')
   Riding.create!(name: 'Yukon', special_riding_id: '940', special_mp_id: '1796')
  end
end